from pathlib import Path
import json,subprocess,hashlib
import argparse,tempfile
parser=argparse.ArgumentParser(description="Actual global key migration and arbitration with isolated MC/IO fixtures; not real input")
parser.add_argument('--java-home',type=Path,required=True)
parser.add_argument('--classpath',type=Path,required=True)
parser.add_argument('--output',type=Path,required=True)
args=parser.parse_args();out=args.output;out.mkdir(parents=True,exist_ok=True)
jdk=args.java_home;deps=args.classpath
sources=Path(__file__).resolve().parents[1]/'src/main/java/net/muxigame/core/client/input'
fixtures={
'com/mojang/blaze3d/platform/InputConstants.java':'''package com.mojang.blaze3d.platform;public class InputConstants{public enum Type{KEYSYM,SCANCODE,MOUSE}public record Key(String getName){public int getValue(){return getName.equals("key.keyboard.tab")?258:getName.startsWith("key.keyboard.")&&getName.length()==14?Character.toUpperCase(getName.charAt(13)):-1;}public Type getType(){return Type.KEYSYM;}}public static Key getKey(String name){return new Key(name);}}''',
'net/neoforged/neoforge/client/settings/KeyModifier.java':'package net.neoforged.neoforge.client.settings;public enum KeyModifier{NONE,SHIFT,CONTROL,ALT}',
'net/minecraft/client/KeyMapping.java':'''package net.minecraft.client;import com.mojang.blaze3d.platform.InputConstants;import net.neoforged.neoforge.client.settings.KeyModifier;public class KeyMapping{String name;InputConstants.Key key;KeyModifier mod;public int clicks;public boolean down;public static int resets;public KeyMapping(String n,String v){name=n;setValue(v);}public void setValue(String v){var p=v.split(":",2);key=InputConstants.getKey(p[0]);mod=p.length==1?KeyModifier.NONE:KeyModifier.valueOf(p[1]);}public String getName(){return name;}public InputConstants.Key getKey(){return key;}public KeyModifier getKeyModifier(){return mod;}public void setKeyModifierAndCode(KeyModifier m,InputConstants.Key k){mod=m;key=k;}public void setDown(boolean v){down=v;}public boolean consumeClick(){if(clicks==0)return false;clicks--;return true;}public static void resetMapping(){resets++;}}''',
'net/minecraft/client/Options.java':'package net.minecraft.client;public class Options{public KeyMapping[] keyMappings;}',
'net/minecraft/client/Minecraft.java':'''package net.minecraft.client;public class Minecraft{public static Minecraft instance=new Minecraft();public java.io.File gameDirectory;public Object player=new Object(),screen;public Options options=new Options();public record Window(long getWindow){}public Window getWindow(){return new Window(100);}public static Minecraft getInstance(){return instance;}}''',
'net/minecraft/client/gui/screens/Screen.java':'package net.minecraft.client.gui.screens;public class Screen{public static boolean shift,ctrl,alt;public static boolean hasShiftDown(){return shift;}public static boolean hasControlDown(){return ctrl;}public static boolean hasAltDown(){return alt;}}',
'net/muxigame/core/client/input/GlobalKeyBindingFixture.java':r'''package net.muxigame.core.client.input;
import java.nio.file.*;import java.util.*;import java.util.concurrent.atomic.*;import net.minecraft.client.*;import net.minecraft.client.gui.screens.Screen;
public class GlobalKeyBindingFixture{
static int n;static void check(boolean value,String description){n++;if(!value)throw new AssertionError(description);}
static KeyMapping mapping(String name,String value){return new KeyMapping(name,value);}
static boolean allow(String name,int key,int mods,boolean f,boolean b,boolean wheel){return GameplayInputPriority.allowed(name,key,mods,true,f,b,wheel);}
static final String ORIGINAL="# preserve comments\r\nlang:zh_cn\r\nkey_key.swapOffhand:key.keyboard.f\r\nkey_key.playerlist:key.keyboard.tab\r\nkey_key.tacz.interact.desc:key.keyboard.o\r\nkey_key.toms_storage.open_terminal:key.keyboard.b:ALT\r\nkey_key.muxi_game_core.challenge_wheel:key.keyboard.b\r\nkey_key.custom.action:key.keyboard.p:SHIFT\r\nkey_key.forward:key.keyboard.up\r\nunknownModChoice:unchanged\r\nresourcePacks:[\"vanilla\",\"file/custom.zip\"]\r\n";
static void migration(Path root)throws Exception{
var mc=Minecraft.instance;mc.gameDirectory=root.toFile();Files.createDirectories(root);Files.writeString(root.resolve("options.txt"),ORIGINAL);
mc.options.keyMappings=GlobalKeyBindingPlan.CHANGES.stream().map(c->mapping(c.name(),c.legacy())).toArray(KeyMapping[]::new);
GlobalKeyBindingMigration.apply(mc.options);var expected=ORIGINAL.replace("swapOffhand:key.keyboard.f","swapOffhand:key.keyboard.tab").replace("playerlist:key.keyboard.tab\r","playerlist:key.keyboard.tab:CONTROL\r").replace("interact.desc:key.keyboard.o","interact.desc:key.keyboard.f").replace("open_terminal:key.keyboard.b:ALT","open_terminal:key.keyboard.t:ALT").replace("challenge_wheel:key.keyboard.b\r","challenge_wheel:key.keyboard.b:ALT\r");
check(Files.readString(root.resolve("options.txt")).equals(expected),"old defaults migrate exactly five keys, preserving other lines/newlines and custom controls");
for(var c:GlobalKeyBindingPlan.CHANGES){var m=Arrays.stream(mc.options.keyMappings).filter(k->k.getName().equals(c.name())).findFirst().orElseThrow();var actual=m.getKey().getName()+(m.getKeyModifier().name().equals("NONE")?"":":"+m.getKeyModifier().name());check(actual.equals(c.desired()),"native loaded mapping changes with saved file: "+c.name());}
var marker=root.resolve("config/muxi_game_core/input-migrations.json");check(Files.exists(marker),"per-key revision marker persisted");var saved=Files.readString(marker);GlobalKeyBindingMigration.apply(mc.options);check(Files.readString(root.resolve("options.txt")).equals(expected)&&Files.readString(marker).equals(saved),"second launch does not rewrite migrated values");
var changed=expected.replace("swapOffhand:key.keyboard.tab","swapOffhand:key.keyboard.g");Files.writeString(root.resolve("options.txt"),changed);mc.options.keyMappings[0].setValue("key.keyboard.g");GlobalKeyBindingMigration.apply(mc.options);check(Files.readString(root.resolve("options.txt")).equals(changed),"post-migration user key choice is preserved");
var other=root.resolve("custom");Files.createDirectories(other);mc.gameDirectory=other.toFile();Files.writeString(other.resolve("options.txt"),"key_key.swapOffhand:key.keyboard.g\nkey_key.playerlist:key.keyboard.p\nkey_key.tacz.interact.desc:key.mouse.2\nkey_key.toms_storage.open_terminal:key.keyboard.l:ALT\nother:keep\n");var custom=Files.readString(other.resolve("options.txt"));mc.options.keyMappings=new KeyMapping[]{mapping(GlobalKeyBindingPlan.SWAP,"key.keyboard.g"),mapping(GlobalKeyBindingPlan.LIST,"key.keyboard.p"),mapping(GlobalKeyBindingPlan.INTERACT,"key.mouse.2"),mapping(GlobalKeyBindingPlan.STORAGE,"key.keyboard.l:ALT")};GlobalKeyBindingMigration.apply(mc.options);check(Files.readString(other.resolve("options.txt")).equals(custom),"non-legacy related custom choices also stay untouched");
var duplicate="key_key.swapOffhand:key.keyboard.f\nkey_key.swapOffhand:key.keyboard.f\nother:keep\n";check(GlobalKeyBindingPlan.updateOptions(duplicate,Map.of(GlobalKeyBindingPlan.SWAP,"key.keyboard.tab")).equals(duplicate.replace("key.keyboard.f","key.keyboard.tab")),"duplicate old key rows cannot resurrect old value on next native load");
check(GlobalKeyBindingPlan.updateOptions("unknown:x",Map.of(GlobalKeyBindingPlan.SWAP,"key.keyboard.tab")).equals("unknown:x\nkey_key.swapOffhand:key.keyboard.tab\n"),"missing affected row appends without modifying unknown text");
var supplied=new HashMap<String,String>();var applied=new HashMap<String,String>();for(var c:GlobalKeyBindingPlan.CHANGES){supplied.put(c.name(),c.desired());applied.put(c.name(),c.desired());}check(GlobalKeyBindingPlan.changes(supplied,applied).isEmpty(),"seed already supplied target bindings needs no runtime rewrite");
check(GlobalKeyBindingPlan.changes(Map.of(GlobalKeyBindingPlan.WHEEL,"key.keyboard.unknown"),Map.of()).equals(Map.of(GlobalKeyBindingPlan.WHEEL,"key.keyboard.b:ALT")),"legacy unbound wheel migrates to AltB");
check(GlobalKeyBindingPlan.changes(Map.of(GlobalKeyBindingPlan.WHEEL,"key.keyboard.g"),Map.of()).isEmpty(),"custom wheel binding stays untouched");
var knownWheel=mapping(GlobalKeyBindingPlan.WHEEL,"key.keyboard.b:ALT");mc.player=new Object();mc.screen=null;check(!GameplayInputPriority.allowed(knownWheel,66),"known native wheel name is guarded without late business registration");
var late=new HashMap<String,String>(applied);late.remove(GlobalKeyBindingPlan.INTERACT);supplied.put(GlobalKeyBindingPlan.INTERACT,"key.keyboard.o");check(GlobalKeyBindingPlan.changes(supplied,late).equals(Map.of(GlobalKeyBindingPlan.INTERACT,"key.keyboard.f")),"later installed mod gets its own migration revision");
}
public static void main(String[] args)throws Exception{
migration(Path.of(args[0]));
check(allow(GlobalKeyBindingPlan.SWAP,258,0,false,false,false),"plain Tab swaps");check(!allow(GlobalKeyBindingPlan.LIST,258,0,false,false,false),"plain Tab does not show player list");check(!allow(GlobalKeyBindingPlan.SWAP,258,2,false,false,false),"CtrlTab does not swap");check(allow(GlobalKeyBindingPlan.LIST,258,2,false,false,false),"CtrlTab player list remains available");
for(int mods:new int[]{1,4,3,6,7,8})check(!allow(GlobalKeyBindingPlan.SWAP,258,mods,false,false,false),"modified Tab never swaps: "+mods);
check(allow(GlobalKeyBindingPlan.INTERACT,70,0,false,false,false),"ordinary F reaches original gun action");check(!allow(GlobalKeyBindingPlan.INTERACT,70,0,true,false,false),"claimed pickup F blocks original gun action");check(!allow(GlobalKeyBindingPlan.INTERACT,70,4,false,false,false),"AltF widget cannot also trigger plain gun F");check(allow("key.accessorify.open_widget",70,4,false,false,false),"AltF widget binding preserved");
for(int mods:new int[]{1,2,3}){check(allow(GlobalKeyBindingPlan.INTERACT,70,mods,false,false,false),"crouch/sprint modifier preserves normal gun F: "+mods);check(!allow(GlobalKeyBindingPlan.INTERACT,70,mods,true,false,false),"claimed movement-modified F still blocks gun: "+mods);}
check(allow("backpack",66,0,false,false,false),"ordinary B backpack remains available");check(!allow("wheel",66,0,false,false,true),"ordinary B never opens weapon wheel");check(allow("wheel",66,4,false,true,true),"AltB wheel permitted");check(!allow("backpack",66,4,false,true,false),"AltB cannot also hit raw B backpack matches");check(!allow("storage",66,4,false,true,false),"old AltB storage conflict suppressed");check(!allow("wheel",66,6,false,true,true),"CtrlAltB does not open AltB wheel");check(allow("boots",66,2,false,false,false),"unrelated CtrlB preserved");check(GameplayInputPriority.allowed("backpack",66,4,false,false,false,false),"normal GUI typing has no global gameplay interception");
var mc=Minecraft.instance;mc.player=new Object();mc.screen=null;var claim=new AtomicBoolean(true);GameplayInputPriority.registerPlainFClaim("outbreak",claim::get);var gun=mapping(GlobalKeyBindingPlan.INTERACT,"key.keyboard.f");mc.options.keyMappings=new KeyMapping[]{gun};GameplayInputPriority.begin(100,70,1,0);check(!GameplayInputPriority.allowed(gun,70),"claim captured before F business callbacks");claim.set(false);check(!GameplayInputPriority.allowed(gun,70),"pickup changing target cannot let same F trigger gun");mc.screen=new Object();check(!GameplayInputPriority.allowed(gun,70),"pickup opening screen keeps same input claim");GameplayInputPriority.end(70,1);mc.screen=null;GameplayInputPriority.begin(100,70,0,0);GameplayInputPriority.end(70,0);check(GameplayInputPriority.allowed(gun,70),"F release clears claim for next ordinary action");
var backpack=mapping("backpack","key.keyboard.b");var wheel=mapping("wheel","key.keyboard.b:ALT");GameplayInputPriority.registerWeaponWheelBinding("wheel");mc.options.keyMappings=new KeyMapping[]{backpack,wheel};GameplayInputPriority.begin(100,66,1,4);check(!GameplayInputPriority.allowed(backpack,66)&&GameplayInputPriority.allowed(wheel,66),"one AltB press routes wheel exclusively");backpack.clicks=3;backpack.down=true;mc.screen=new Object();GameplayInputPriority.releaseAll();check(!GameplayInputPriority.allowed(backpack,66),"wheel screen init cannot undo same-event reservation");GameplayInputPriority.end(66,1);check(backpack.clicks==0&&!backpack.down,"blocked backpack queue and held state drained at event end");mc.screen=null;Screen.alt=false;check(!GameplayInputPriority.allowed(backpack,66),"releasing Alt while B stays held cannot leak backpack action");GameplayInputPriority.begin(100,66,0,0);GameplayInputPriority.end(66,0);check(GameplayInputPriority.allowed(backpack,66),"B release restores normal backpack binding");check(!GameplayInputPriority.allowed(wheel,66),"plain B remains rejected for wheel after prior AltB");
var send=new AtomicInteger();var context=new AtomicBoolean(true);GameplayInputPriority.registerPlainFAction("equipment-input",context::get,()->{send.incrementAndGet();context.set(false);});mc.screen=null;mc.options.keyMappings=new KeyMapping[]{gun};GameplayInputPriority.begin(100,70,1,0);GameplayInputPriority.dispatchPlainF();GameplayInputPriority.dispatchPlainF();check(send.get()==1,"one F press sends one original server-validated interact request");check(!GameplayInputPriority.allowed(gun,70),"dispatch changing context cannot also trigger TACZ in the same F event");GameplayInputPriority.end(70,1);check(!GameplayInputPriority.begin(999,70,0,0),"foreign window callback is ignored");check(!GameplayInputPriority.allowed(gun,70),"foreign F release cannot clear active game claim");GameplayInputPriority.begin(100,70,2,0);GameplayInputPriority.dispatchPlainF();check(send.get()==1,"held F repeat cannot submit a second interaction");GameplayInputPriority.end(70,2);GameplayInputPriority.begin(100,70,0,0);GameplayInputPriority.end(70,0);check(GameplayInputPriority.allowed(gun,70),"ordinary gun F restored after leaving claimed interaction");
net.muxigame.core.feature.input.GameInputContextState.accept("outbreak","test:campaign");check(net.muxigame.core.feature.input.GameInputContextState.claimsOutbreak("test:campaign"),"server Outbreak context claims matching current dimension");check(!net.muxigame.core.feature.input.GameInputContextState.claimsOutbreak("minecraft:overworld"),"stale context after dimension change cannot claim ordinary F");net.muxigame.core.feature.input.GameInputContextState.accept("zombie","test:campaign");check(!net.muxigame.core.feature.input.GameInputContextState.claimsOutbreak("test:campaign"),"other minigame context does not take Outbreak F");net.muxigame.core.feature.input.GameInputContextState.reset();check(!net.muxigame.core.feature.input.GameInputContextState.claimsOutbreak("test:campaign"),"logout clears server-issued input context");
mc.options.keyMappings=new KeyMapping[]{gun};context.set(true);GameplayInputPriority.begin(100,70,1,1);GameplayInputPriority.dispatchPlainF();check(send.get()==2,"crouched F sends one original pickup request");check(!GameplayInputPriority.allowed(gun,70),"crouched pickup F cannot also trigger gun interaction");GameplayInputPriority.end(70,1);GameplayInputPriority.begin(100,70,0,1);GameplayInputPriority.end(70,0);
var customTab=mapping(GlobalKeyBindingPlan.LIST,"key.keyboard.tab:SHIFT");mc.options.keyMappings=new KeyMapping[]{customTab};GameplayInputPriority.begin(100,258,1,1);check(GameplayInputPriority.allowed(customTab,258),"custom ShiftTab player list remains usable");GameplayInputPriority.end(258,1);GameplayInputPriority.begin(100,258,1,2);check(!GameplayInputPriority.allowed(customTab,258),"custom ShiftTab list does not also trigger on default CtrlTab");GameplayInputPriority.end(258,1);
var customF=mapping(GlobalKeyBindingPlan.INTERACT,"key.keyboard.f:ALT");mc.options.keyMappings=new KeyMapping[]{customF};GameplayInputPriority.begin(100,70,1,4);check(GameplayInputPriority.allowed(customF,70),"explicit custom AltF gun modifier remains usable");GameplayInputPriority.end(70,1);
System.out.println("{\"success\":true,\"checks\":"+n+",\"scope\":\"actual migration and arbitration classes with file/native-state fixtures; not physical input\"}");
}}
'''
}
paths=[]
for name,data in fixtures.items():
 p=out/'src'/name;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(data,encoding='utf-8');paths.append(p)
actual=[sources/name for name in ['GlobalKeyBindingPlan.java','GlobalKeyBindingMigration.java','GameplayInputPriority.java']]
actual.append(sources.parents[1]/'feature/input/GameInputContextState.java')
classes=out/'classes';classes.mkdir(exist_ok=True)
compile=subprocess.run([str(jdk/'bin/javac.exe'),'--release','21','-encoding','UTF-8','-cp',str(deps),'-d',str(classes),*map(str,actual+paths)],capture_output=True,text=True,encoding='utf-8');assert compile.returncode==0,compile.stderr
run=subprocess.run([str(jdk/'bin/java.exe'),'-cp',str(classes)+';'+str(deps),'net.muxigame.core.client.input.GlobalKeyBindingFixture',tempfile.mkdtemp(prefix='case-files-',dir=out)],capture_output=True,text=True,encoding='utf-8');assert run.returncode==0,run.stdout+run.stderr
result=json.loads(run.stdout);result['sources']={p.name:hashlib.sha256(p.read_bytes()).hexdigest() for p in actual};result.update({'realInput':False,'newMcStarted':False})
(out/'result.json').write_text(json.dumps(result,indent=2),encoding='utf-8');print(json.dumps(result))
