package net.muxigame.transferqa;
import com.google.gson.*;
import net.minecraft.client.Minecraft;
import net.minecraft.client.Screenshot;
import net.minecraft.client.gui.screens.TitleScreen;
import net.neoforged.api.distmarker.Dist;
import net.neoforged.fml.common.Mod;
import net.neoforged.neoforge.common.NeoForge;
import net.neoforged.neoforge.client.event.ClientTickEvent;
import net.neoforged.neoforge.client.event.RenderLevelStageEvent;
import java.nio.file.*;
import java.time.Instant;
import java.util.*;
/** Native offline join/reconnect only. Prepared world is never teleported or modified. */

@Mod(value="muxi_transfer_qa",dist=Dist.CLIENT)
public final class JoinNativeQA {
 private JsonObject loggingGate()throws Exception{
  Class<?> type=Class.forName("net.muxigame.core.compat.logging.CreativeTraceGate");
  var current=type.getDeclaredField("current");current.setAccessible(true);Object lease=current.get(null);
  var reason=type.getDeclaredField("unavailableReason");reason.setAccessible(true);
  JsonObject result=new JsonObject();result.addProperty("requested",Boolean.getBoolean("muxi.creativeTraceGate"));
  result.addProperty("reason",String.valueOf(reason.get(null)));boolean valid=false;
  if(lease!=null){var method=lease.getClass().getDeclaredMethod("valid");method.setAccessible(true);valid=(Boolean)method.invoke(lease);}
  result.addProperty("activeValidLease",valid);return result;
 }

 private final Gson gson=new GsonBuilder().setPrettyPrinting().create();
 private final JsonObject report=new JsonObject();private final JsonArray samples=new JsonArray();
 private JsonObject sample;private int ticks,wait,moveTicks,index;private long begin,ready,moved;private double x,z;
 private boolean disconnecting,finished,checking;private volatile boolean checked,serverMoved;
 public JoinNativeQA(){NeoForge.EVENT_BUS.addListener(this::tick);NeoForge.EVENT_BUS.addListener(this::render);report.addProperty("method","Native offline integrated server join and reconnect without fixture setup or teleport; external authentication/resource synchronization not measured");}
 private JsonElement reflection(String type,String method)throws Exception{return gson.toJsonTree(Class.forName(type).getMethod(method).invoke(null));}
 private JsonElement binaries()throws Exception{return reflection("net.muxigame.core.compat.shaders.ShaderProgramBinary","snapshot");}
 private JsonElement stages()throws Exception{return gson.toJsonTree(net.muxigame.binaryqa.Trace.snapshot());}
 private JsonObject shader()throws Exception{Class<?> iris=Class.forName("net.irisshaders.iris.Iris");JsonObject value=new JsonObject();value.addProperty("fallback",(Boolean)iris.getMethod("isFallback").invoke(null));Object config=iris.getMethod("getIrisConfig").invoke(null);value.addProperty("enabled",(Boolean)config.getClass().getMethod("areShadersEnabled").invoke(config));Object manager=iris.getMethod("getPipelineManager").invoke(null);Object pipeline=manager.getClass().getMethod("getPipeline").invoke(manager);value.addProperty("pipeline",pipeline.toString());return value;}
 private net.minecraft.client.KeyMapping movementKey(Minecraft mc){return index%2==0?mc.options.keyDown:mc.options.keyUp;}
 private JsonObject position(Minecraft mc){JsonObject p=new JsonObject();if(mc.player!=null){p.addProperty("x",mc.player.getX());p.addProperty("y",mc.player.getY());p.addProperty("z",mc.player.getZ());p.addProperty("yaw",mc.player.getYRot());p.addProperty("onGround",mc.player.onGround());}return p;}
 private void write()throws Exception{report.add("samples",samples);Files.writeString(Path.of("latency-join-result.json"),gson.toJson(report));}
 private void render(RenderLevelStageEvent event){if(finished||disconnecting||sample==null||ready!=0||event.getStage()!=RenderLevelStageEvent.Stage.AFTER_LEVEL)return;Minecraft mc=Minecraft.getInstance();if(mc.level==null||mc.player==null||mc.screen!=null||mc.getOverlay()!=null||!mc.level.hasChunkAt(mc.player.blockPosition())||!mc.levelRenderer.isSectionCompiled(mc.player.blockPosition()))return;ready=System.nanoTime();net.muxigame.binaryqa.route.RouteTimeline.mark("qualifiedVisible");sample.addProperty("visibleNs",ready);var boundary=net.muxigame.binaryqa.Trace.snapshot();sample.add("nativeStagesAtVisible",gson.toJsonTree(boundary));long login=((Number)boundary.get("loginBeginNs")).longValue();sample.addProperty("clientLoginToVisibleMs",(ready-login)/1e6);sample.addProperty("visibleAndInputUnblockedMs",(ready-begin)/1e6);sample.addProperty("dimension",mc.level.dimension().location().toString());x=mc.player.getX();z=mc.player.getZ();sample.add("positionAtVisible",position(mc));sample.addProperty("movementKey",index%2==0?"backward":"forward");movementKey(mc).setDown(true);}
 private void tick(ClientTickEvent.Post event){if(finished)return;Minecraft mc=Minecraft.getInstance();try{
  ticks++;if(Files.exists(Path.of("request-normal-close.json"))||ticks>24000)throw new IllegalStateException("QA deadline");
  if(disconnecting){if(mc.level!=null||mc.getSingleplayerServer()!=null||++wait<40)return;JsonObject cache=binaries().getAsJsonObject();sample.add("programBinariesAfterLogout",cache);if(cache.get("memoryEntries").getAsInt()!=0||cache.get("memoryBytes").getAsLong()!=0||cache.get("sourceMetadata").getAsInt()!=0||cache.get("bindingMetadata").getAsInt()!=0)throw new IllegalStateException("Program metadata retained after join logout");JsonObject swapAfterLogout=reflection("net.muxigame.core.compat.shaders.DimensionShaderSwap","diagnosticLifecycleSnapshot").getAsJsonObject();sample.add("parsedPackCacheAfterLogout",swapAfterLogout);if(swapAfterLogout.get("parsedPacks").getAsInt()!=0||swapAfterLogout.get("capturedPackRoot").getAsBoolean()||swapAfterLogout.get("pendingLevel").getAsBoolean())throw new IllegalStateException("Dimension shader state retained after logout");net.muxigame.binaryqa.NativeProbe.dump("native-join-"+index+".json");net.muxigame.binaryqa.CreativeOrigins.dump();samples.add(sample);sample=null;write();index++;disconnecting=false;wait=0;if(index>=3){report.addProperty("success",true);report.addProperty("normalLogout",true);write();finished=true;new TransferNativeQA();}return;}
  if(sample==null){if(!(mc.screen instanceof TitleScreen)||mc.getOverlay()!=null||ticks<60)return;if(!Files.isDirectory(Path.of("saves/transfer-private")))throw new IllegalStateException("Prepared native join world required");net.muxigame.binaryqa.NativeProbe.reset();net.muxigame.binaryqa.Trace.clearSpans();sample=new JsonObject();sample.addProperty("cachePhase",net.muxigame.core.compat.shaders.VeilShaderEventDispatch.enabled()?"on":"off");sample.addProperty("index",index);sample.addProperty("joinKind",index==0?"new-process":"same-process-reconnect");sample.addProperty("requestedUtc",Instant.now().toString());sample.addProperty("binaryRequested",Boolean.getBoolean("muxi.programBinaryCache"));sample.addProperty("loggingRequested",Boolean.getBoolean("muxi.creativeTraceGate"));sample.add("loggingGateBefore",loggingGate());sample.add("programBinariesBefore",binaries());sample.add("veilDispatchBefore",gson.toJsonTree(net.muxigame.core.compat.shaders.VeilShaderEventDispatch.snapshot()));sample.add("shaderStagesBefore",stages());begin=System.nanoTime();net.muxigame.binaryqa.route.RouteTimeline.begin("join-"+index,"minecraft:overworld",Double.NaN,Double.NaN,Double.NaN);ready=moved=0;moveTicks=0;checking=checked=serverMoved=false;mc.createWorldOpenFlows().openWorld("transfer-private",()->{});return;}
  long now=System.nanoTime();if(now-begin>240_000_000_000L)throw new IllegalStateException("Native join >240s");if(ready==0)return;if(++moveTicks>=5){mc.options.keyUp.setDown(false);mc.options.keyDown.setDown(false);}
  if(moved==0){if(Math.hypot(mc.player.getX()-x,mc.player.getZ()-z)>.025){moved=now;sample.addProperty("movementResponseMs",(now-begin)/1e6);sample.add("positionAfterMovement",position(mc));}else if(now-ready>10_000_000_000L)throw new IllegalStateException("Native join input blocked");return;}
  if(now-moved<5_000_000_000L)return;if(!checking){checking=true;UUID uuid=mc.player.getUUID();double startX=x,startZ=z;mc.getSingleplayerServer().execute(()->{var player=mc.getSingleplayerServer().getPlayerList().getPlayer(uuid);serverMoved=player!=null&&Math.hypot(player.getX()-startX,player.getZ()-startZ)>.025;checked=true;});return;}if(!checked)return;if(!serverMoved)throw new IllegalStateException("Server did not observe join movement");sample.addProperty("serverObservedMovement",true);net.muxigame.binaryqa.route.RouteTimeline.mark("serverObservedMovement");net.muxigame.binaryqa.route.RouteTimeline.end("join-complete");net.muxigame.binaryqa.route.RouteTimeline.dump("timeline-join-"+index+".json");
  JsonObject state=shader();if(!state.get("enabled").getAsBoolean()||state.get("fallback").getAsBoolean()||!state.get("pipeline").getAsString().contains("IrisRenderingPipeline"))throw new IllegalStateException("Native join shader mismatch "+state);sample.add("shaderState",state);sample.add("dimensionSwapAfter",reflection("net.muxigame.core.compat.shaders.DimensionShaderSwap","diagnosticSnapshot"));sample.addProperty("veilPropertyAbsent",System.getProperty("muxi.veilShaderEventDispatch")==null);sample.add("loggingGateAfter",loggingGate());sample.add("programBinariesAfter",binaries());sample.add("veilDispatchAfter",gson.toJsonTree(net.muxigame.core.compat.shaders.VeilShaderEventDispatch.snapshot()));sample.add("shaderStagesAfter",stages());try(var png=Screenshot.takeScreenshot(mc.getMainRenderTarget())){png.writeToFile(Path.of("join-"+index+".png"));}mc.options.keyUp.setDown(false);mc.options.keyDown.setDown(false);mc.level.disconnect();mc.disconnect(new TitleScreen());disconnecting=true;wait=0;
 }catch(Throwable failure){finished=true;mc.options.keyUp.setDown(false);mc.options.keyDown.setDown(false);report.addProperty("success",false);report.addProperty("error",failure.toString());report.add("failurePlayer",position(mc));if(sample!=null)report.add("failedSample",sample);failure.printStackTrace();try{write();}catch(Exception ignored){}try{net.muxigame.binaryqa.route.RouteTimeline.end("failure");net.muxigame.binaryqa.route.RouteTimeline.dump("timeline-failed-join.json");}catch(Exception ignored){}if(mc.level!=null){mc.level.disconnect();mc.disconnect(new TitleScreen());}mc.stop();}}
}
