package net.muxigame.shadernative;
import com.google.gson.*;import java.util.*;import java.util.concurrent.*;import java.lang.reflect.*;
import net.neoforged.fml.common.Mod;import net.neoforged.api.distmarker.Dist;import net.neoforged.neoforge.common.NeoForge;import net.neoforged.neoforge.client.event.*;
import net.minecraft.client.Minecraft;import net.minecraft.client.gui.screens.*;import net.minecraft.client.multiplayer.ServerData;import net.minecraft.client.multiplayer.resolver.ServerAddress;
import net.muxigame.memoryqa.MemoryLifecycleProbe;import net.muxigame.binaryqa.Trace;import net.muxigame.binaryqa.route.RouteTimeline;
/** Business-only state machine. Common local_mc_debug owns processes and normal shutdown. */
@Mod(value="muxi_shader_native_qa",dist=Dist.CLIENT)
public final class ClientQA {
 private static ClientQA instance;private boolean firstSpawn;private JsonObject previousSpawnFinish;
 private final JsonObject report=new JsonObject();private final JsonArray samples=new JsonArray(),logouts=new JsonArray();
 private JsonObject sample,ack,baseline;private int phase,joinIndex,routeIndex=-1,ticks,wait,moveTicks,commandId;private boolean commandPending,commandAck,finalLogout;
 private long begin,visible,inputStart;private double px,pz,tx,ty;private String uuid,routeId,target="minecraft:overworld";private CompletableFuture<Void> resourceReload;
 public ClientQA(){if(FilesQA.enabled()){instance=this;report.addProperty("method","Real loopback TCP; first connection plus two reconnects, original eight native routes; no integrated server access");report.addProperty("clockDomain",ProcessHandle.current().pid());report.addProperty("physicalOSInput",false);report.addProperty("platformFixture","Pre-existing world landing platforms required; no forced loading or world edits by QA");NeoForge.EVENT_BUS.addListener(this::tick);NeoForge.EVENT_BUS.addListener(this::render);}}
 public static void connecting(ServerAddress address){if(instance==null||!FilesQA.enabled())return;try{if(!address.getHost().equals("127.0.0.1")||address.getPort()!=FilesQA.port)throw new IllegalStateException("Unexpected non-QA connection");instance.startCase(false);}catch(Throwable failure){instance.fail(failure);}}
 public static void loginThreadBoundary(String dimension){if(instance==null||JoinObservation.token()==0)return;try{instance.sample.addProperty("loginPacketDimension",dimension);JoinObservation.event(JoinObservation.token(),"loginPacketDimension",dimension);require(!instance.firstSpawn||dimension.equals("muxi_game_core:overworld"),"First-spawn initial login packet is not Core overworld");JoinObservation.logging(instance.logging(),"handleLogin-after-thread-check",true);}catch(Exception failure){instance.fail(failure);}}
 private void observeJoin(){if(JoinObservation.token()==0)return;var mc=Minecraft.getInstance();JoinObservation.ui(mc.screen==null?"null":mc.screen.getClass().getName(),mc.getOverlay()==null?"null":mc.getOverlay().getClass().getName());if(ticks%20==0)try{JoinObservation.logging(logging(),"clientTick20",false);}catch(Exception failure){JoinObservation.event(JoinObservation.token(),"loggingObservationFailed",failure.getClass().getName());}}
 private void validateSpawn(JsonObject receipt,boolean finishing)throws Exception{require(receipt.has("firstSpawn"),"Missing first-spawn server observation");var state=receipt.getAsJsonObject("firstSpawn");require(!state.has("probeError"),"First-spawn observer failed: "+state);require(state.get("freshPlayerDataAbsentBeforeConnect").getAsBoolean(),"First-spawn account was not fresh");require(state.get("done").getAsBoolean()&&!state.get("pendingPresent").getAsBoolean(),"Initial spawn state not DONE/cleared");require(state.get("dimension").getAsString().equals("muxi_game_core:overworld"),"Spawn not in Core overworld");require(state.get("uuid").getAsString().equals(state.get("expectedUuid").getAsString()),"Unexpected first-spawn UUID");require(!state.get("connectionRequestPresent").getAsBoolean()&&state.get("requestCountAll").getAsInt()==0,"Spawn request retained after login");var login=state.getAsJsonObject("lastLogin");require(login!=null&&login.get("dimension").getAsString().equals("muxi_game_core:overworld"),"Initial login dimension differs");require(login.get("radiusBlockSquared").getAsLong()<=100_000_000L,"Spawn exceeds native radius");if(joinIndex==0)require(login.has("safeInitialSpawn")&&login.get("safeInitialSpawn").getAsBoolean(),"Native initial landing is not observed safe");if(!finishing&&previousSpawnFinish!=null){require(login.get("uuid").equals(previousSpawnFinish.get("uuid")),"Reconnect changed UUID");for(String axis:List.of("x","y","z"))require(Math.abs(login.get(axis).getAsDouble()-previousSpawnFinish.get(axis).getAsDouble())<(axis.equals("y")?1.01:.05),"Reconnect changed saved "+axis);for(var entry:login.getAsJsonArray("requests")){var request=entry.getAsJsonObject();require(request.get("attempts").getAsInt()==0&&!request.get("searchPresent").getAsBoolean(),"Reconnect began a new random search");}}sample.add(finishing?"firstSpawnFinish":"firstSpawnBaseline",state);if(finishing)previousSpawnFinish=state.deepCopy();}
 private static Object call(String type,String method)throws Exception{return PerformanceProbe.type(type).getMethod(method).invoke(null);}
 private static JsonObject object(String type,String method)throws Exception{return FilesQA.object(call(type,method));}
 private static void require(boolean ok,String why){if(!ok)throw new IllegalStateException(why);}
 private JsonObject player(){var mc=Minecraft.getInstance();var p=new JsonObject();if(mc.player!=null){p.addProperty("x",mc.player.getX());p.addProperty("y",mc.player.getY());p.addProperty("z",mc.player.getZ());p.addProperty("dimension",mc.level.dimension().location().toString());}return p;}
 private static void verifyMacro(JsonObject diagnostic,Map<?,?> defines,String nativeDimension){
  String macro="CURRENT_EUPHORIA_PATCHES_DIMENSION_"+nativeDimension.toUpperCase(Locale.ROOT);
  var keys=new JsonArray();defines.keySet().stream().map(Object::toString).filter(k->k.startsWith("CURRENT_EUPHORIA_PATCHES_DIMENSION_")).sorted().forEach(keys::add);
  diagnostic.addProperty("nativeDimension",nativeDimension);diagnostic.addProperty("expectedMacro",macro);diagnostic.add("actualDimensionMacroKeys",keys);diagnostic.addProperty("FIRST_LOADED",defines.containsKey("EUPHORIA_PATCHES_FIRST_LOADED"));diagnostic.addProperty("firstLoaded",defines.containsKey("EUPHORIA_PATCHES_FIRST_LOADED"));diagnostic.addProperty("EUPHORIA_PATCHES_DIMENSION_IN_PROPERTIES",defines.containsKey("EUPHORIA_PATCHES_DIMENSION_IN_PROPERTIES"));diagnostic.addProperty("sourceMacroCount",defines.size());diagnostic.addProperty("dimensionMacro",macro);
  require(defines.containsKey(macro)&&keys.size()==1,"Incorrect dimension macro");
 }
 private JsonObject shader()throws Exception{
  var j=new JsonObject();report.add("lastShaderObservation",j);if(sample!=null)sample.add("shader",j);var mc=Minecraft.getInstance();j.addProperty("currentLevel",mc.level==null?"null":mc.level.dimension().location().toString());
  try{var count=Class.forName("com.euphoriapatches.euphoria_patcher.integration.DefineHelper",false,ClientQA.class.getClassLoader()).getDeclaredField("injectCount");count.setAccessible(true);j.addProperty("injectCount",count.getInt(null));}catch(ReflectiveOperationException|RuntimeException|LinkageError unavailable){j.addProperty("injectCountDiagnosticError",unavailable.getClass().getName());}try{var last=Minecraft.class.getDeclaredField("euphoriaPatcher$lastDimension");last.setAccessible(true);j.addProperty("lastDimension",String.valueOf(last.get(null)));}catch(ReflectiveOperationException|RuntimeException|LinkageError unavailable){j.addProperty("lastDimensionDiagnosticError",unavailable.getClass().getName());}
  var iris=Class.forName("net.irisshaders.iris.Iris");boolean fallback=(Boolean)iris.getMethod("isFallback").invoke(null);Object cfg=iris.getMethod("getIrisConfig").invoke(null);boolean enabled=(Boolean)cfg.getClass().getMethod("areShadersEnabled").invoke(cfg);Object manager=iris.getMethod("getPipelineManager").invoke(null);String pipeline=manager.getClass().getMethod("getPipeline").invoke(manager).toString();j.addProperty("enabled",enabled);j.addProperty("fallback",fallback);j.addProperty("pipeline",pipeline);
  require(enabled&&!fallback&&pipeline.contains("IrisRenderingPipeline"),"Native shader pipeline unavailable");
  Field f=iris.getDeclaredField("currentPack");f.setAccessible(true);Object pack=f.get(null);j.addProperty("currentPackPresent",pack!=null);require(pack!=null,"Missing native shader pack");j.addProperty("currentPackIdentity",Integer.toHexString(System.identityHashCode(pack)));Object source=PerformanceProbe.type("net.muxigame.core.compat.shaders.ShaderPackSourceCarrier").getMethod("muxi$shaderPackSource").invoke(pack);j.addProperty("sourcePresent",source!=null);j.addProperty("sourceIdentity",Integer.toHexString(System.identityHashCode(source)));Map<?,?> defines=(Map<?,?>)source.getClass().getMethod("defines").invoke(source);
  verifyMacro(j,defines,String.valueOf(call("com.euphoriapatches.euphoria_patcher.util.mod.ModLoaderSpecifics","getCurrentDimensionStatic")));return j;
 }

 private JsonObject logging()throws Exception{var c=PerformanceProbe.type("net.muxigame.core.compat.logging.CreativeTraceGate");var f=c.getDeclaredField("current");f.setAccessible(true);Object lease=f.get(null);var j=new JsonObject();j.addProperty("leasePresent",lease!=null);j.addProperty("propertyAbsent",System.getProperty("muxi.creativeTraceGate")==null);if(lease!=null){for(String n:List.of("valid","rejectsTrace")){var m=lease.getClass().getDeclaredMethod(n);m.setAccessible(true);j.addProperty(n,(Boolean)m.invoke(lease));}}return j;}
 private JsonObject defaultLogging()throws Exception{var j=logging();require(j.get("propertyAbsent").getAsBoolean()&&j.has("valid")&&j.get("valid").getAsBoolean()&&j.has("rejectsTrace")&&j.get("rejectsTrace").getAsBoolean(),"Default logging filter not rejecting trace: "+j);return j;}
 private JsonObject loggingRollback()throws Exception{var j=new JsonObject();j.add("before",defaultLogging());var c=PerformanceProbe.type("net.muxigame.core.compat.logging.CreativeTraceGate");var tick=c.getMethod("update");try{for(String value:List.of("false","invalid")){System.setProperty("muxi.creativeTraceGate",value);tick.invoke(null);var state=logging();require(!state.get("leasePresent").getAsBoolean(),"Logging lease retained for "+value);j.add(value,state);}}finally{System.clearProperty("muxi.creativeTraceGate");tick.invoke(null);}j.add("restored",defaultLogging());return j;}
 private void send(String op)throws Exception{require(!commandPending,"Overlapping business commands");JsonObject q=new JsonObject();q.addProperty("id",++commandId);q.addProperty("op",op);q.addProperty("routeId",routeId==null?"lifecycle":routeId);q.addProperty("dimension",target);if(uuid!=null)q.addProperty("uuid",uuid);q.addProperty("x",tx);q.addProperty("y",ty);q.addProperty("z",8.5);FilesQA.write("server-command.json",q);commandPending=true;ack=null;}
 private void poll()throws Exception{if(!commandPending)return;var a=FilesQA.read("server-result-"+commandId+".json");if(a==null)return;require(a.get("id").getAsInt()==commandId&&a.get("routeId").getAsString().equals(routeId==null?"lifecycle":routeId),"Mismatched business receipt");require(a.get("ok").getAsBoolean(),"Server callback failed: "+a);ack=a;commandPending=false;}
 private void startCase(boolean transfer)throws Exception{
  var mc=Minecraft.getInstance();firstSpawn=FilesQA.firstSpawn();report.add("profile",FilesQA.profile());if(firstSpawn){report.addProperty("method","First-spawn profile: fresh account plus two reconnects in Core overworld; no QA teleport, fixed routes or movement input");report.addProperty("platformFixture","Native random safe first-spawn; observes already-loaded blocks only");}require(!firstSpawn||!transfer,"First-spawn mode never sends route commands");require(phase==0||phase==7||phase==8,"Unexpected connection/case re-entry");routeId=transfer?"route-"+routeIndex:"join-"+joinIndex;target=transfer?(routeIndex==4?"muxi_game_core:adventure":routeIndex==6?"muxi_game_core:overworld":"minecraft:overworld"):(firstSpawn?"muxi_game_core:overworld":"minecraft:overworld");tx=transfer&&routeIndex==2?16392.5:8.5;ty=transfer&&routeIndex==0?224:241;
  if(!transfer)JoinObservation.begin(routeId);Trace.reset();RouteTimeline.begin(routeId,target,transfer?tx:Double.NaN,transfer?ty:Double.NaN,transfer?8.5:Double.NaN);begin=System.nanoTime();visible=0;wait=moveTicks=0;commandAck=false;sample=new JsonObject();sample.addProperty("routeId",routeId);sample.addProperty("clientBeginNs",begin);sample.addProperty("kind",transfer?"route":"TCP join");var loggingBefore=logging();sample.add("loggingBefore",loggingBefore);if(!transfer)JoinObservation.logging(loggingBefore,"connectStart",true);sample.add("memoryBefore",MemoryLifecycleProbe.snapshot(transfer?"route_before":"connect_menu_before"));sample.addProperty("expectedPipelineCreated",transfer?(routeIndex<4?0:1):1);phase=1;observeJoin();if(mc.player!=null)uuid=mc.player.getUUID().toString();send(transfer?"route":"arm");
 }
 private void render(RenderLevelStageEvent e){if(phase!=1||visible!=0||e.getStage()!=RenderLevelStageEvent.Stage.AFTER_LEVEL)return;var mc=Minecraft.getInstance();if(mc.player==null||mc.level==null||mc.screen!=null||mc.getOverlay()!=null||!mc.level.dimension().location().toString().equals(target)||!mc.level.hasChunkAt(mc.player.blockPosition())||!mc.levelRenderer.isSectionCompiled(mc.player.blockPosition()))return;if(routeIndex>=0&&(Math.abs(mc.player.getX()-tx)>3||Math.abs(mc.player.getY()-ty)>3||Math.abs(mc.player.getZ()-8.5)>3))return;try{require(mc.getConnection()!=null&&FilesQA.loopback(mc.getConnection().getConnection().getRemoteAddress()),"Not real loopback TCP");visible=System.nanoTime();uuid=mc.player.getUUID().toString();sample.addProperty(routeIndex<0?"clientConnectToVisibleMs":"clientRequestToVisibleMs",(visible-begin)/1e6);if(routeIndex<0){long login=((Number)Trace.snapshot().get("clientLoginNs")).longValue();require(login>=begin&&login<=visible,"Missing comparable handleLogin boundary");sample.addProperty("clientHandleLoginToVisibleMs",(visible-login)/1e6);sample.addProperty("clientHandleLoginNs",login);}sample.addProperty("qualifiedVisibleClientNs",visible);sample.add("visiblePosition",player());sample.add("memoryVisible",MemoryLifecycleProbe.snapshot("visible"));RouteTimeline.mark("qualifiedVisible");observeJoin();if(routeIndex<0)sample.add("joinObservation",JoinObservation.finish());}catch(Throwable failure){fail(failure);}}
 private void release(){var mc=Minecraft.getInstance();mc.options.keyUp.setDown(false);mc.options.keyDown.setDown(false);}
 private void disconnect(boolean last)throws Exception{var mc=Minecraft.getInstance();release();uuid=mc.player.getUUID().toString();mc.level.disconnect();mc.disconnect(new TitleScreen());finalLogout=last;wait=0;var state=object("net.muxigame.core.compat.shaders.DimensionShaderSwap","diagnosticLifecycleSnapshot");require(state.get("parsedPacks").getAsInt()==0&&!state.get("capturedPackRoot").getAsBoolean()&&!state.get("pendingLevel").getAsBoolean(),"Swap retains logout state");var bins=object("net.muxigame.core.compat.shaders.ShaderProgramBinary","snapshot");for(String key:List.of("memoryEntries","memoryBytes","sourceMetadata","bindingMetadata"))require(bins.get(key).getAsLong()==0,"Binary cache retains "+key);var l=new JsonObject();l.addProperty("after",routeId);l.add("swap",state);l.add("binary",bins);l.add("memory",MemoryLifecycleProbe.snapshot("logout_menu"));logouts.add(l);send("absent");phase=6;}
 private void completeCase()throws Exception{if(firstSpawn)validateSpawn(ack,true);sample.add("shader",shader());long pipelines=Trace.count("pipelineCreated");sample.addProperty("pipelineCreated",pipelines);require(pipelines==sample.get("expectedPipelineCreated").getAsLong(),"Unexpected actual pipeline creation count for "+routeId+": "+pipelines);sample.add("loggingAfter",defaultLogging());sample.add("memoryComplete",MemoryLifecycleProbe.snapshot("case_complete"));sample.add("dimensionSwap",object("net.muxigame.core.compat.shaders.DimensionShaderSwap","diagnosticSnapshot"));sample.add("clientTrace",FilesQA.JSON.toJsonTree(Trace.snapshot()));RouteTimeline.end("complete");sample.add("clientTimeline",FilesQA.JSON.toJsonTree(RouteTimeline.snapshot()));sample.add("serverFinish",ack);Trace.ready=false;samples.add(sample);sample=null;write();if(routeIndex<0){if(joinIndex<2){joinIndex++;disconnect(false);}else if(firstSpawn){startReloadChecks();}else {routeIndex=0;phase=8;wait=0;}}else if(++routeIndex<8){phase=8;wait=0;}else {startReloadChecks();}}
 private void startReloadChecks()throws Exception{report.add("memoryBeforeIrisReload",MemoryLifecycleProbe.snapshot("before_iris_reload"));Trace.reset();call("net.irisshaders.iris.Iris","reload");require(object("net.muxigame.core.compat.shaders.DimensionShaderSwap","diagnosticSnapshot").size()==0,"Iris reload retained swap snapshot");report.add("irisReloadShader",shader());require(Trace.count("pipelineCreated")>=1,"Iris reload did not construct pipeline");report.add("irisReloadTrace",FilesQA.JSON.toJsonTree(Trace.snapshot()));report.add("memoryAfterIrisReload",MemoryLifecycleProbe.snapshot("after_iris_reload"));report.add("memoryBeforeResourceReload",MemoryLifecycleProbe.snapshot("before_resource_reload"));Trace.reset();resourceReload=Minecraft.getInstance().reloadResourcePacks();phase=9;wait=0;}

 private void tick(ClientTickEvent.Post e){ticks++;if(phase==10)return;if(FilesQA.stopping()){release();return;}try{observeJoin();poll();if(phase==0)return;if(phase!=7&&phase!=8&&System.nanoTime()-begin>300_000_000_000L)throw new IllegalStateException("Business phase timeout "+phase);var mc=Minecraft.getInstance();switch(phase){
 case 1->{if(ack!=null){sample.add("serverStart",ack);commandAck=true;ack=null;}if(commandAck&&visible!=0){send("position");phase=2;}}
 case 2->{if(ack!=null){if(firstSpawn)validateSpawn(ack,false);baseline=ack.getAsJsonObject("player");require(baseline.get("tcpLoopback").getAsBoolean(),"Missing server TCP proof");px=mc.player.getX();pz=mc.player.getZ();inputStart=System.nanoTime();if(firstSpawn){sample.addProperty("nativeMovementCheck",false);phase=4;wait=0;}else {mc.options.keyUp.setDown(true);phase=3;}ack=null;}}
 case 3->{if(++moveTicks>=5)release();if(System.nanoTime()-inputStart>10_000_000_000L)throw new IllegalStateException("Input/server movement not acknowledged");if(ack!=null){var sp=ack.getAsJsonObject("player");if(Math.hypot(sp.get("x").getAsDouble()-baseline.get("x").getAsDouble(),sp.get("z").getAsDouble()-baseline.get("z").getAsDouble())>.025){sample.add("serverMovement",ack);sample.addProperty("movementClientMs",(System.nanoTime()-inputStart)/1e6);phase=4;wait=0;release();}ack=null;}if(phase==3&&!commandPending&&Math.hypot(mc.player.getX()-px,mc.player.getZ()-pz)>.025)send("position");}
 case 4->{if(++wait>=100){send("finish");phase=5;}}
 case 5->{if(ack!=null){completeCase();ack=null;}}
 case 6->{if(ack!=null){boolean absent=ack.get("absent").getAsBoolean();if(absent){if(firstSpawn){var state=ack.getAsJsonObject("firstSpawn");require(state!=null&&!state.has("probeError")&&state.get("requestCountAll").getAsInt()==0,"Initial-spawn request retained after logout");}logouts.get(logouts.size()-1).getAsJsonObject().add("serverAbsent",ack);}ack=null;if(absent){if(finalLogout){report.addProperty("passed",true);phase=10;Trace.ready=false;write();}else{phase=7;wait=0;}}else send("absent");}}
 case 7->{if(++wait>=40){require(mc.level==null&&mc.player==null,"Client did not disconnect");ConnectScreen.startConnecting(new TitleScreen(),mc,ServerAddress.parseString("127.0.0.1:"+FilesQA.port),new ServerData("Shader native QA","127.0.0.1:"+FilesQA.port,ServerData.Type.OTHER),false,null);}}
 case 8->{if(++wait>=40)startCase(true);}
 case 9->{if(resourceReload.isDone()){resourceReload.join();if(mc.getOverlay()!=null||mc.screen!=null){wait=0;break;}if(++wait>=60){report.add("resourceReloadShader",shader());report.add("resourceReloadTrace",FilesQA.JSON.toJsonTree(Trace.snapshot()));report.addProperty("resourceReloadCompleted",true);report.add("memoryAfterResourceReload",MemoryLifecycleProbe.snapshot("after_resource_reload"));report.add("loggingRollback",loggingRollback());Trace.ready=false;disconnect(true);}}}
 default->throw new IllegalStateException("Unknown phase");}
 }catch(Throwable failure){fail(failure);}}
 private void write()throws Exception{report.add("samples",samples);report.add("logouts",logouts);report.addProperty("phase",phase);FilesQA.write("client-result.json",report);}
 private void fail(Throwable failure){if(sample!=null&&JoinObservation.token()!=0)sample.add("joinObservation",JoinObservation.finish());release();phase=10;Trace.ready=false;report.addProperty("passed",false);report.addProperty("error",failure.toString());if(sample!=null){sample.add("traceAtFailure",FilesQA.JSON.toJsonTree(Trace.snapshot()));sample.add("clientTimelineAtFailure",FilesQA.JSON.toJsonTree(RouteTimeline.snapshot()));try{sample.add("dimensionSwapAtFailure",object("net.muxigame.core.compat.shaders.DimensionShaderSwap","diagnosticSnapshot"));sample.add("dimensionSwapLifecycleAtFailure",object("net.muxigame.core.compat.shaders.DimensionShaderSwap","diagnosticLifecycleSnapshot"));}catch(Exception diagnosticFailure){sample.addProperty("dimensionSwapDiagnosticError",diagnosticFailure.toString());}report.add("failedSample",sample);}try{write();}catch(Exception io){failure.addSuppressed(io);}failure.printStackTrace();}
}
