package net.muxigame.shadernative;
import com.google.gson.*;import java.nio.file.*;import java.net.*;import java.util.*;
public final class FilesQA {
 public static final Gson JSON=new GsonBuilder().setPrettyPrinting().create();
 public static final String RUN=System.getProperty("qa.local.runId",""),ROLE=System.getProperty("qa.local.role","");
 public static final Path ROOT=Path.of(System.getProperty("qa.local.root","missing-root")).toAbsolutePath().normalize();
 private static boolean checked,enabled;public static int port;
 public static synchronized boolean enabled(){if(checked)return enabled;checked=true;try{if(RUN.isBlank())return false;var owner=JsonParser.parseString(readText(ROOT.resolve("local-mc-owner.json"))).getAsJsonObject();port=owner.get("serverPort").getAsInt();enabled=owner.get("runId").getAsString().equals(RUN)&&Path.of(owner.get("instanceRoot").getAsString()).toAbsolutePath().normalize().equals(ROOT)&&owner.get("offlineLoopback").getAsBoolean()&&owner.get("mode").getAsString().equals("hold")&&owner.getAsJsonArray("roles").contains(new JsonPrimitive(ROLE))&&port>0&&port<65536&&owner.getAsJsonArray("roles").size()==2;if(enabled)Files.createDirectories(home());return enabled;}catch(Exception e){return false;}}
 public static Path home(){return ROOT.resolve("coordinator/shader-native");}
 public static boolean loopback(java.net.SocketAddress address){return address instanceof InetSocketAddress a&&a.getAddress()!=null&&a.getAddress().isLoopbackAddress();}
 // Bounded Windows sharing-lock retries. Callers keep command IDs and receipts across retries.
 private static void backoff(int attempt)throws java.io.IOException {try{Thread.sleep(5L*(attempt+1));}catch(InterruptedException e){Thread.currentThread().interrupt();throw new java.io.IOException("Interrupted QA file retry",e);}}
 private static String readText(Path path)throws java.io.IOException {for(int attempt=0;;attempt++){try{return Files.readString(path);}catch(NoSuchFileException missing){throw missing;}catch(FileSystemException locked){if(attempt>=5)throw locked;backoff(attempt);}}}
 public static JsonObject read(String name)throws java.io.IOException {try{var j=JsonParser.parseString(readText(home().resolve(name))).getAsJsonObject();return j.has("runId")&&RUN.equals(j.get("runId").getAsString())?j:null;}catch(NoSuchFileException missing){return null;}catch(JsonParseException e){return null;}}
 public static void write(String name,JsonObject data)throws java.io.IOException {if(!enabled())throw new IllegalStateException("Not a private single-client hold lab");data.addProperty("runId",RUN);var p=home().resolve(name);var tmp=p.resolveSibling(p.getFileName()+"."+UUID.randomUUID()+".tmp");try{String body=JSON.toJson(data);for(int attempt=0;;attempt++){try{Files.writeString(tmp,body);break;}catch(FileSystemException locked){if(attempt>=5)throw locked;backoff(attempt);}}for(int attempt=0;;attempt++){try{try{Files.move(tmp,p,StandardCopyOption.ATOMIC_MOVE,StandardCopyOption.REPLACE_EXISTING);}catch(AtomicMoveNotSupportedException unsupported){Files.move(tmp,p,StandardCopyOption.REPLACE_EXISTING);}break;}catch(FileSystemException locked){if(attempt>=5)throw locked;backoff(attempt);}}}finally{try{Files.deleteIfExists(tmp);}catch(java.io.IOException ignored){}}}
 private static JsonObject profile;
 public static synchronized JsonObject profile()throws java.io.IOException {if(profile!=null)return profile.deepCopy();if(!enabled())throw new IllegalStateException("Private lab required");var path=home().resolve("config.json");JsonObject value;if(Files.exists(path)){value=JsonParser.parseString(readText(path)).getAsJsonObject();if(!value.has("runId")||!RUN.equals(value.get("runId").getAsString()))throw new IllegalStateException("Business config runId mismatch");}else{try(var stream=FilesQA.class.getResourceAsStream("/shader-native-profile.json")){value=stream==null?new JsonObject():JsonParser.parseString(new String(stream.readAllBytes(),java.nio.charset.StandardCharsets.UTF_8)).getAsJsonObject();}}for(String key:value.keySet())if(!Set.of("runId","mode","expectedPlayer").contains(key))throw new IllegalStateException("Unknown business profile field "+key);String mode=value.has("mode")?value.get("mode").getAsString():"matrix";if(!Set.of("matrix","first-spawn").contains(mode))throw new IllegalStateException("Unknown business mode");value.addProperty("mode",mode);if(mode.equals("first-spawn")){String player=value.has("expectedPlayer")?value.get("expectedPlayer").getAsString():"";if(!player.matches("[A-Za-z0-9_]{1,16}"))throw new IllegalStateException("Explicit fresh player required");var owner=JsonParser.parseString(readText(ROOT.resolve("local-mc-owner.json"))).getAsJsonObject();if(!owner.getAsJsonObject("clientNames").get("host").getAsString().equals(player))throw new IllegalStateException("First-spawn expected player differs from owned client");}profile=value;return value.deepCopy();}
 public static boolean firstSpawn()throws java.io.IOException{return profile().get("mode").getAsString().equals("first-spawn");}
 public static JsonObject object(Object data){return JSON.toJsonTree(data).getAsJsonObject();}
 public static boolean stopping(){return Files.exists(ROOT.resolve("stop-request.json"));}
 private FilesQA(){}
}
