package net.muxigame.shadernative;
import com.google.gson.*;import net.neoforged.fml.common.Mod;import net.neoforged.api.distmarker.Dist;import net.neoforged.neoforge.common.NeoForge;import net.neoforged.neoforge.event.tick.ServerTickEvent;import net.minecraft.server.level.*;import net.minecraft.resources.*;import net.minecraft.core.registries.Registries;import net.minecraft.world.level.portal.DimensionTransition;import net.minecraft.world.phys.Vec3;import net.muxigame.binaryqa.Trace;import java.util.*;import net.neoforged.neoforge.event.entity.player.PlayerEvent;
@Mod(value="muxi_shader_native_qa",dist=Dist.DEDICATED_SERVER)
public final class ServerQA {
 private int last=-1;private JsonObject pending,readySnapshot;private boolean readyWritten,loginDirty;private long firstPostTickNs,firstLoginNs;private int loginCount;private final JsonArray logins=new JsonArray();
 public ServerQA(){if(FilesQA.enabled()){NeoForge.EVENT_BUS.addListener(this::tick);NeoForge.EVENT_BUS.addListener(this::loggedIn);}}
 // Observation only: never call update() or install a missing gate.
 private JsonObject logging(int players){var j=new JsonObject();j.addProperty("serverNanoTime",System.nanoTime());j.addProperty("clockDomain",ProcessHandle.current().pid());j.addProperty("defaultPropertyAbsent",System.getProperty("muxi.creativeTraceGate")==null);j.addProperty("players",players);j.addProperty("firstPostTickNs",firstPostTickNs);j.addProperty("firstLoginEventNs",firstLoginNs);j.addProperty("loginEvents",loginCount);if(firstLoginNs!=0&&firstPostTickNs!=0)j.addProperty("readyObservedBeforeFirstLoginEvent",firstPostTickNs<firstLoginNs);try{var c=Class.forName("net.muxigame.core.compat.logging.CreativeTraceGate",false,ServerQA.class.getClassLoader());var f=c.getDeclaredField("current");f.setAccessible(true);Object lease=f.get(null);j.addProperty("leasePresent",lease!=null);j.addProperty("valid",false);j.addProperty("rejectsTrace",false);if(lease!=null){for(String name:List.of("valid","rejectsTrace")){var method=lease.getClass().getDeclaredMethod(name);method.setAccessible(true);j.addProperty(name,(Boolean)method.invoke(lease));}}}catch(ReflectiveOperationException|LinkageError|RuntimeException failure){j.addProperty("probeError",failure.toString());}return j;}
 private void loggedIn(PlayerEvent.PlayerLoggedInEvent event){if(!(event.getEntity() instanceof ServerPlayer player))return;SpawnObservation.login(player);long now=System.nanoTime();if(firstLoginNs==0)firstLoginNs=now;loginCount++;if(logins.size()<16){var row=new JsonObject();row.addProperty("serverNanoTime",now);row.addProperty("uuid",player.getUUID().toString());row.addProperty("tcpLoopback",FilesQA.loopback(player.connection.getConnection().getRemoteAddress()));row.addProperty("readyObservedBeforeLoginEvent",firstPostTickNs!=0&&firstPostTickNs<now);logins.add(row);}loginDirty=true;}
 private void observations(ServerTickEvent.Post event)throws java.io.IOException{if(readySnapshot==null){firstPostTickNs=System.nanoTime();readySnapshot=logging(event.getServer().getPlayerCount());readySnapshot.addProperty("boundary","first ServerTickEvent.Post callback; not server startup or packet arrival");}if(!readyWritten){FilesQA.write("server-logging-ready.json",readySnapshot);readyWritten=true;}if(loginDirty){var j=new JsonObject();j.addProperty("clockDomain",ProcessHandle.current().pid());j.addProperty("firstPostTickNs",firstPostTickNs);j.addProperty("firstLoginEventNs",firstLoginNs);j.addProperty("loginEvents",loginCount);j.addProperty("dropped",Math.max(0,loginCount-16));j.addProperty("boundary","PlayerLoggedInEvent on dedicated server; no cross-process timestamp subtraction");j.add("events",logins);FilesQA.write("server-login-timeline.json",j);loginDirty=false;}}
 private static JsonObject position(ServerPlayer p){var j=new JsonObject();j.addProperty("uuid",p.getUUID().toString());j.addProperty("dimension",p.level().dimension().location().toString());j.addProperty("x",p.getX());j.addProperty("y",p.getY());j.addProperty("z",p.getZ());j.addProperty("tcpLoopback",FilesQA.loopback(p.connection.getConnection().getRemoteAddress()));return j;}
 private void tick(ServerTickEvent.Post e){if(FilesQA.stopping())return;try{SpawnObservation.tick(e.getServer());observations(e);if(pending!=null){FilesQA.write("server-result-"+last+".json",pending);pending=null;}var q=FilesQA.read("server-command.json");if(q==null||q.get("id").getAsInt()<=last)return;last=q.get("id").getAsInt();var a=new JsonObject();a.addProperty("id",last);a.addProperty("routeId",q.get("routeId").getAsString());a.addProperty("clockDomain",ProcessHandle.current().pid());long start=System.nanoTime();try{var server=e.getServer();String op=q.get("op").getAsString();if(op.equals("arm")){Trace.reset();ServerTimeline.begin(q.get("dimension").getAsString());}
 else {UUID uuid=UUID.fromString(q.get("uuid").getAsString());var p=server.getPlayerList().getPlayer(uuid);if(op.equals("absent")){a.addProperty("absent",p==null);if(FilesQA.firstSpawn())a.add("firstSpawn",SpawnObservation.snapshot(server,p));}
 else {if(p==null||!FilesQA.loopback(p.connection.getConnection().getRemoteAddress()))throw new IllegalStateException("Expected real loopback TCP player");if(op.equals("route")){if(FilesQA.firstSpawn())throw new IllegalStateException("No QA route mutations in first-spawn mode");String dim=q.get("dimension").getAsString();var level=server.getLevel(ResourceKey.create(Registries.DIMENSION,ResourceLocation.parse(dim)));if(level==null)throw new IllegalStateException("Missing target dimension "+dim);Trace.reset();ServerTimeline.begin(dim);double x=q.get("x").getAsDouble(),y=q.get("y").getAsDouble(),z=q.get("z").getAsDouble();long move=System.nanoTime();if(p.level()==level)p.teleportTo(x,y,z);else {var moved=p.changeDimension(new DimensionTransition(level,new Vec3(x,y,z),Vec3.ZERO,180,15,DimensionTransition.DO_NOTHING));if(!(moved instanceof ServerPlayer))throw new IllegalStateException("Native changeDimension rejected");p=(ServerPlayer)moved;}a.addProperty("serverEngineMs",(System.nanoTime()-move)/1e6);}
 else if(op.equals("finish")){a.add("trace",FilesQA.JSON.toJsonTree(Trace.snapshot()));a.add("timeline",FilesQA.JSON.toJsonTree(ServerTimeline.snapshot()));ServerTimeline.end();Trace.ready=false;}
 else if(!op.equals("position"))throw new IllegalArgumentException("Unknown shader QA operation");a.add("player",position(p));if(FilesQA.firstSpawn())a.add("firstSpawn",SpawnObservation.snapshot(server,p));}}
 a.addProperty("ok",true);}catch(Throwable failure){a.addProperty("ok",false);a.addProperty("error",failure.toString());}a.addProperty("serverCallbackMs",(System.nanoTime()-start)/1e6);if(Set.of("arm","route","finish").contains(q.get("op").getAsString()))a.add("logging",logging(e.getServer().getPlayerCount()));pending=a;FilesQA.write("server-result-"+last+".json",pending);pending=null;
 }catch(java.io.IOException retry){System.err.println("SHADER_NATIVE_QA_FILE_RETRY "+retry.getClass().getSimpleName());}}
}
