package net.muxigame.shadernative;
import com.google.gson.*;import java.lang.reflect.*;import java.nio.charset.StandardCharsets;import java.nio.file.Files;import java.util.*;
import net.minecraft.server.MinecraftServer;import net.minecraft.server.level.ServerPlayer;import net.minecraft.world.level.storage.LevelResource;
/** Private QA, server-thread confined. Reads existing state only, never requests a chunk or writes NBT. */
public final class SpawnObservation {
 private static UUID expected;private static boolean checked,fresh;private static long firstTick;private static String previous;private static int dropped;private static final JsonArray transitions=new JsonArray(),logins=new JsonArray();
 private static final Map<String,Field> fields=new HashMap<>();private static Class<?> preparation;private static JsonObject lastLogin;
 private static Object field(Object receiver,Class<?> type,String name)throws Exception{String key=type.getName()+"#"+name;Field f=fields.get(key);if(f==null){f=type.getDeclaredField(name);f.setAccessible(true);fields.put(key,f);}return f.get(receiver);}
 private static Map<?,?> requests(MinecraftServer server)throws Exception{if(preparation==null)preparation=Class.forName("net.muxigame.core.feature.dimensions.initialspawn.InitialSpawnPreparation",false,SpawnObservation.class.getClassLoader());var managers=(Map<?,?>)field(null,preparation,"MANAGERS");Object manager=managers.get(server);return manager==null?Map.of():(Map<?,?>)field(manager,manager.getClass(),"requests");}
 private static JsonObject request(Object value)throws Exception{var out=new JsonObject();out.addProperty("uuid",field(value,value.getClass(),"id").toString());out.addProperty("ticket",((Number)field(value,value.getClass(),"ticket")).longValue());out.addProperty("finished",(Boolean)field(value,value.getClass(),"finished"));out.addProperty("consumed",(Boolean)field(value,value.getClass(),"consumed"));Object search=field(value,value.getClass(),"search");out.addProperty("searchPresent",search!=null);out.addProperty("attempts",search==null?0:((Number)search.getClass().getMethod("attempts").invoke(search)).intValue());return out;}
 public static void tick(MinecraftServer server){try{if(!FilesQA.firstSpawn())return;if(!checked){checked=true;firstTick=server.getTickCount();String name=FilesQA.profile().get("expectedPlayer").getAsString();expected=UUID.nameUUIDFromBytes(("OfflinePlayer:"+name).getBytes(StandardCharsets.UTF_8));fresh=!Files.exists(server.getWorldPath(LevelResource.PLAYER_DATA_DIR).resolve(expected+".dat"))&&!Files.exists(server.getWorldPath(LevelResource.PLAYER_DATA_DIR).resolve(expected+".dat_old"));}var state=state(server,null);String signature=state.get("requests").toString();if(!signature.equals(previous)){previous=signature;var row=new JsonObject();row.addProperty("serverNanoTime",System.nanoTime());row.addProperty("serverTick",server.getTickCount());row.add("requests",state.get("requests"));if(transitions.size()<32)transitions.add(row);else dropped++;}}catch(Exception|LinkageError failure){error=failure.toString();}}
 private static String error;
 public static JsonObject state(MinecraftServer server,ServerPlayer player)throws Exception{var out=new JsonObject();out.addProperty("serverNanoTime",System.nanoTime());out.addProperty("serverTick",server.getTickCount());out.addProperty("firstObservedServerTick",firstTick);out.addProperty("clockDomain",ProcessHandle.current().pid());out.addProperty("freshPlayerDataAbsentBeforeConnect",fresh);out.addProperty("expectedUuid",expected==null?"":expected.toString());var rows=new JsonArray();var requests=requests(server);for(Object v:requests.values()){var row=request(v);if(row.get("uuid").getAsString().equals(String.valueOf(expected)))rows.add(row);}out.add("requests",rows);out.addProperty("requestCountAll",requests.size());if(player!=null){out.addProperty("connectionRequestPresent",requests.containsKey(player.connection.getConnection()));var nbt=player.getPersistentData().getCompound("PlayerPersisted");out.addProperty("done",nbt.getBoolean("muxiInitialSurvivalDone"));out.addProperty("pendingPresent",nbt.contains("muxiInitialSurvivalPending"));out.addProperty("pending",nbt.getBoolean("muxiInitialSurvivalPending"));out.addProperty("book",nbt.getBoolean("muxiFirstJoinBook"));out.addProperty("uuid",player.getUUID().toString());out.addProperty("name",player.getGameProfile().getName());out.addProperty("dimension",player.serverLevel().dimension().location().toString());out.addProperty("x",player.getX());out.addProperty("y",player.getY());out.addProperty("z",player.getZ());}if(error!=null)out.addProperty("probeError",error);if(lastLogin!=null)out.add("lastLogin",lastLogin.deepCopy());return out;}
 public static void login(ServerPlayer player){try{if(!FilesQA.firstSpawn())return;var row=state(player.server,player);row.remove("lastLogin");var pos=player.blockPosition();row.addProperty("radiusBlockSquared",(long)pos.getX()*pos.getX()+(long)pos.getZ()*pos.getZ());boolean loaded=true;for(int x=(pos.getX()-6)>>4;x<=(pos.getX()+6)>>4;x++)for(int z=(pos.getZ()-6)>>4;z<=(pos.getZ()+6)>>4;z++)loaded&=player.serverLevel().getChunkSource().getChunkNow(x,z)!=null;row.addProperty("safetyFootprintAlreadyLoaded",loaded);if(loaded){var method=Class.forName("net.muxigame.core.feature.dimensions.DimensionsFeature").getMethod("safeInitialSpawn",net.minecraft.server.level.ServerLevel.class,net.minecraft.core.BlockPos.class);row.addProperty("safeInitialSpawn",(Boolean)method.invoke(null,player.serverLevel(),pos));}lastLogin=row;if(logins.size()<3)logins.add(row.deepCopy());else dropped++;}catch(Exception|LinkageError failure){error=failure.toString();}}
 public static JsonObject snapshot(MinecraftServer server,ServerPlayer player){try{var out=state(server,player);out.add("requestTransitions",transitions.deepCopy());out.add("loginEvents",logins.deepCopy());out.addProperty("transitionCap",32);out.addProperty("dropped",dropped);out.addProperty("limitation","Tick/request snapshots are sampled; same UUID plus persisted positions and DONE prove observed reuse, not statistical uniformity or complete ticket ledger");return out;}catch(Exception|LinkageError failure){var out=new JsonObject();out.addProperty("probeError",failure.toString());return out;}}
 private SpawnObservation(){}
}
