"""Execute production server adapters, native guard hooks and protocol against deterministic world/API doubles.
No real world, game, account, network connection or operator configuration is modified.
"""
from pathlib import Path
import subprocess,tempfile,json,os
root=Path(__file__).resolve().parent
files={
'net/minecraft/resources/ResourceLocation.java':'''package net.minecraft.resources; public record ResourceLocation(String value) {public static ResourceLocation fromNamespaceAndPath(String n,String p){return new ResourceLocation(n+":"+p);}public static ResourceLocation tryParse(String s){return s.contains(":")?new ResourceLocation(s):null;}public String getNamespace(){return value.split(":")[0];}public String toString(){return value;}}''',
'net/minecraft/resources/ResourceKey.java':'''package net.minecraft.resources;public record ResourceKey<T>(ResourceLocation location){public static <T> ResourceKey<T> create(Object registry,ResourceLocation location){return new ResourceKey<>(location);}}''',
'net/minecraft/core/registries/Registries.java':'''package net.minecraft.core.registries;public class Registries{public static final Object DIMENSION=new Object();}''',
'net/minecraft/core/BlockPos.java':'''package net.minecraft.core;public record BlockPos(int getX,int getY,int getZ){public BlockPos immutable(){return this;}public BlockPos offset(int x,int y,int z){return new BlockPos(getX+x,getY+y,getZ+z);}public double distSqr(BlockPos p){return Math.pow(getX-p.getX,2)+Math.pow(getY-p.getY,2)+Math.pow(getZ-p.getZ,2);}}''',
'net/minecraft/core/Direction.java':'''package net.minecraft.core;public class Direction{public enum Axis{X,Z;public String getName(){return name();}}}''',
'net/minecraft/network/chat/Component.java':'''package net.minecraft.network.chat;public record Component(String getString){public static Component literal(String s){return new Component(s);}public static Component translatable(String s){return new Component(s);}}''',
'net/minecraft/world/level/Level.java':'''package net.minecraft.world.level;import net.minecraft.resources.*;public class Level{public ResourceKey<Level> dimension;public ResourceKey<Level> dimension(){return dimension;}}''',
'net/minecraft/world/level/block/state/BlockState.java':'''package net.minecraft.world.level.block.state;public record BlockState(Object getBlock){}''',
'net/minecraft/world/entity/Entity.java':'''package net.minecraft.world.entity;public class Entity{}''',
'net/minecraft/server/level/ServerLevel.java':'''package net.minecraft.server.level;import java.util.*;import net.minecraft.core.*;import net.minecraft.world.level.*;import net.minecraft.world.level.block.state.*;public class ServerLevel extends Level{public net.minecraft.server.MinecraftServer server;public net.minecraft.server.MinecraftServer getServer(){return server;}public final Map<BlockPos,Object> blocks=new HashMap<>();public boolean loaded=true;public int reads,unloadedReads,worldWrites;public final Set<BlockPos> unloaded=new HashSet<>();public ServerLevel(String d){dimension=net.minecraft.resources.ResourceKey.create(null,net.minecraft.resources.ResourceLocation.tryParse(d));}public boolean hasChunkAt(BlockPos p){return loaded&&!unloaded.contains(p);}public BlockState getBlockState(BlockPos p){reads++;if(!hasChunkAt(p))unloadedReads++;return new BlockState(blocks.get(p));}public int getMinBuildHeight(){return -64;}public int getMaxBuildHeight(){return 320;}}''',
'net/minecraft/server/MinecraftServer.java':'''package net.minecraft.server;import java.util.*;import net.minecraft.server.level.*;import net.minecraft.resources.*;import net.minecraft.world.level.Level;public class MinecraftServer{public final Map<ResourceKey<Level>,ServerLevel> levels=new HashMap<>();public ServerPlayer player;public ServerLevel getLevel(ResourceKey<Level> k){return levels.get(k);}public MinecraftServer getPlayerList(){return this;}public ServerPlayer getPlayer(UUID uid){return player!=null&&player.getUUID().equals(uid)?player:null;}public void execute(Runnable r){r.run();}}''',
'net/minecraft/server/level/ServerPlayer.java':'''package net.minecraft.server.level;import net.minecraft.server.*;import net.minecraft.core.*;import java.util.*;import net.minecraft.network.chat.*;public class ServerPlayer extends net.minecraft.world.entity.Entity{public final MinecraftServer server;public Object connection=new Object();public ServerLevel level;public BlockPos pos=new BlockPos(0,64,0);public int tickCount;public boolean alive=true,disconnected,activated=true;public final UUID uid=UUID.randomUUID();public final List<String> messages=new ArrayList<>();public ServerPlayer(MinecraftServer s,ServerLevel l){server=s;level=l;s.player=this;}public ServerLevel serverLevel(){return level;}public BlockPos blockPosition(){return pos;}public boolean isAlive(){return alive;}public boolean hasDisconnected(){return disconnected;}public UUID getUUID(){return uid;}public void displayClientMessage(Component c,boolean actionbar){messages.add(c.getString());}}''',
'net/muxigame/core/feature/dimensions/WorldPortalBlock.java':'''package net.muxigame.core.feature.dimensions;public record WorldPortalBlock(int destination){}''',
'net/muxigame/core/feature/dimensions/WorldDimensions.java':'''package net.muxigame.core.feature.dimensions;public class WorldDimensions{public record World(net.minecraft.resources.ResourceKey<net.minecraft.world.level.Level> key){}public static final java.util.List<World>ALL=java.util.List.of(new World(net.minecraft.resources.ResourceKey.create(null,net.minecraft.resources.ResourceLocation.tryParse("minecraft:overworld"))),new World(net.minecraft.resources.ResourceKey.create(null,net.minecraft.resources.ResourceLocation.tryParse("muxi_game_core:overworld"))));public static boolean managed(net.minecraft.resources.ResourceKey<net.minecraft.world.level.Level> k){return ALL.stream().anyMatch(w->w.key().equals(k));}}''',
'net/muxigame/core/feature/dimensions/WorldPortals.java':'''package net.muxigame.core.feature.dimensions;import net.minecraft.core.*;import net.minecraft.server.level.*;import java.util.*;public class WorldPortals{public record Frame(BlockPos origin,Direction.Axis axis,int destination){public BlockPos at(int w,int h){return origin.offset(w,h,0);}public String key(ServerLevel l){return l.dimension().location()+"/"+origin+"/"+axis;}}public static final Map<BlockPos,Frame> frames=new HashMap<>();public static Frame find(ServerLevel l,BlockPos p,int d,boolean active){return frames.get(p);}}''',
'net/muxigame/minigames/GameRuntime.java':'''package net.muxigame.minigames;public class GameRuntime{public static boolean locked;public static boolean blocksWorldTravel(net.minecraft.server.level.ServerPlayer p){return locked;}}''',
'net/neoforged/fml/loading/FMLPaths.java':'''package net.neoforged.fml.loading;import java.nio.file.*;public enum FMLPaths{CONFIGDIR;public Path get(){return Path.of(System.getProperty("test.config"));}}''',
'net/blay09/mods/waystones/block/WaystoneBlockBase.java':'''package net.blay09.mods.waystones.block;public class WaystoneBlockBase{}''',
'net/blay09/mods/waystones/api/Waystone.java':'''package net.blay09.mods.waystones.api;import java.util.*;import net.minecraft.core.*;import net.minecraft.resources.*;import net.minecraft.world.level.*;public class Waystone{public final UUID uid=UUID.randomUUID();public BlockPos pos;public ResourceKey<Level> dimension;public boolean valid=true,share;public Waystone(ResourceKey<Level>d,BlockPos p){dimension=d;pos=p;}public UUID getWaystoneUid(){return uid;}public BlockPos getPos(){return pos;}public ResourceKey<Level> getDimension(){return dimension;}public boolean isValid(){return valid;}public ResourceLocation getWaystoneType(){return ResourceLocation.tryParse(share?"waystones:sharestone":"waystones:waystone");}}''',
'net/blay09/mods/waystones/api/WaystoneTypes.java':'''package net.blay09.mods.waystones.api;public class WaystoneTypes{public static boolean isSharestone(net.minecraft.resources.ResourceLocation type){return type.toString().equals("waystones:sharestone");}}''',
'net/blay09/mods/waystones/api/WaystoneTeleportContext.java':'''package net.blay09.mods.waystones.api;public class WaystoneTeleportContext{public final net.minecraft.server.level.ServerPlayer player;public final Waystone target;public Waystone source;public WaystoneTeleportContext(net.minecraft.server.level.ServerPlayer p,Waystone t){player=p;target=t;}public void setFromWaystone(Waystone s){source=s;}public Waystone getTargetWaystone(){return target;}public net.minecraft.world.entity.Entity getEntity(){return player;}}''',
'net/blay09/mods/waystones/api/error/WaystoneTeleportError.java':'''package net.blay09.mods.waystones.api.error;public record WaystoneTeleportError(net.minecraft.network.chat.Component getComponent){}''',
'net/blay09/mods/waystones/api/EntityTeleportResult.java':'''package net.blay09.mods.waystones.api;import net.blay09.mods.waystones.api.error.*;public record EntityTeleportResult(WaystoneTeleportError error){public static EntityTeleportResult failed(net.minecraft.world.entity.Entity e,Object dest,WaystoneTeleportError err){return new EntityTeleportResult(err);}}''',
'net/blay09/mods/waystones/api/event/WaystoneTeleportEntityEvent.java':'''package net.blay09.mods.waystones.api.event;import net.blay09.mods.waystones.api.*;public class WaystoneTeleportEntityEvent{public static class Pre{public WaystoneTeleportContext context;public EntityTeleportResult override;public Pre(WaystoneTeleportContext c){context=c;}public WaystoneTeleportContext getContext(){return context;}public net.minecraft.world.entity.Entity getEntity(){return context.getEntity();}public Object getOriginalDestination(){return null;}public void overrideResult(EntityTeleportResult r){override=r;}}}''',
'net/blay09/mods/balm/api/Balm.java':'''package net.blay09.mods.balm.api;import java.util.*;import java.util.function.*;public class Balm{public static final Events events=new Events();public static Events getEvents(){return events;}public static class Events{public final Map<Class<?>,Consumer<Object>> handlers=new HashMap<>();public <T>void onEvent(Class<T> c,Consumer<T> h){handlers.put(c,e->h.accept(c.cast(e)));}public void fire(Object e){var h=handlers.get(e.getClass());if(h!=null)h.accept(e);}}}''',
'net/minecraft/network/RegistryFriendlyByteBuf.java':'''package net.minecraft.network;import java.util.*;import net.minecraft.resources.*;import net.minecraft.core.*;public class RegistryFriendlyByteBuf{public final List<Object> values=new ArrayList<>();public int cursor;public void writeUUID(UUID v){values.add(v);}public UUID readUUID(){return (UUID)values.get(cursor++);}public void writeResourceLocation(ResourceLocation v){values.add(v);}public ResourceLocation readResourceLocation(){return (ResourceLocation)values.get(cursor++);}public void writeBlockPos(BlockPos v){values.add(v);}public BlockPos readBlockPos(){return (BlockPos)values.get(cursor++);}public void writeBoolean(boolean v){values.add(v);}public boolean readBoolean(){return (boolean)values.get(cursor++);}public void writeVarInt(int v){values.add(v);}public int readVarInt(){return (int)values.get(cursor++);}public void writeUtf(String v,int max){if(v.length()>max)throw new IllegalArgumentException();values.add(v);}public String readUtf(int max){String v=(String)values.get(cursor++);if(v.length()>max)throw new IllegalArgumentException();return v;}}''',
'net/minecraft/network/codec/StreamCodec.java':'''package net.minecraft.network.codec;import java.util.function.*;public record StreamCodec<B,V>(BiConsumer<B,V> encoder,Function<B,V> decoder){public static <B,V>StreamCodec<B,V>of(BiConsumer<B,V> w,Function<B,V>r){return new StreamCodec<>(w,r);}public void encode(B b,V v){encoder.accept(b,v);}public V decode(B b){return decoder.apply(b);}}''',
'net/minecraft/network/protocol/common/custom/CustomPacketPayload.java':'''package net.minecraft.network.protocol.common.custom;public interface CustomPacketPayload{record Type<T>(net.minecraft.resources.ResourceLocation id){}Type<?>type();}''',
'net/neoforged/bus/api/IEventBus.java':'''package net.neoforged.bus.api;public class IEventBus{public void addListener(java.util.function.Consumer<net.neoforged.neoforge.network.event.RegisterPayloadHandlersEvent> listener){listener.accept(new net.neoforged.neoforge.network.event.RegisterPayloadHandlersEvent());}}''',
'net/neoforged/neoforge/network/event/RegisterPayloadHandlersEvent.java':'''package net.neoforged.neoforge.network.event;import java.util.*;import java.util.function.*;import net.minecraft.network.protocol.common.custom.*;import net.minecraft.network.codec.*;import net.minecraft.network.*;public class RegisterPayloadHandlersEvent{public record Context(Object player){}public static final Map<String,BiConsumer<CustomPacketPayload,Context>> handlers=new HashMap<>();public Registrar registrar(String v){return new Registrar();}public static class Registrar{public Registrar optional(){return this;}public <T extends CustomPacketPayload>void playToServer(CustomPacketPayload.Type<T> t,StreamCodec<RegistryFriendlyByteBuf,T> codec,BiConsumer<T,Context> h){handlers.put(t.id().toString(),(p,c)->h.accept((T)p,c));}public <T extends CustomPacketPayload>void playToClient(CustomPacketPayload.Type<T> t,StreamCodec<RegistryFriendlyByteBuf,T> codec,BiConsumer<T,Context> h){}}}''',
'net/neoforged/neoforge/network/registration/NetworkRegistry.java':'''package net.neoforged.neoforge.network.registration;public class NetworkRegistry{public static boolean hasChannel(Object c,net.minecraft.resources.ResourceLocation id){return c!=null;}}''',
'net/neoforged/neoforge/network/PacketDistributor.java':'''package net.neoforged.neoforge.network;import java.util.*;import net.minecraft.network.protocol.common.custom.*;public class PacketDistributor{public static final List<CustomPacketPayload> sent=new ArrayList<>();public static void sendToPlayer(net.minecraft.server.level.ServerPlayer p,CustomPacketPayload packet){sent.add(packet);}public static void sendToServer(CustomPacketPayload p){sent.add(p);}}''',
}

# The controlled Waystones double preserves native preparation / final validation / cost / movement ordering.
files['net/blay09/mods/waystones/api/WaystonesAPI.java']='''package net.blay09.mods.waystones.api;
import java.util.*;import java.util.concurrent.*;import java.util.function.*;import java.util.stream.*;
import net.minecraft.server.*;import net.minecraft.server.level.*;import net.minecraft.core.*;import net.minecraft.world.entity.Entity;
import net.blay09.mods.waystones.api.error.*;import com.mojang.datafixers.util.Either;
public class WaystonesAPI {
 public static final Map<UUID,Waystone> stones=new LinkedHashMap<>();public static boolean originalDenied,noMovement;public static int creates,starts,fees,moves;
 public static WaystoneTeleportContext pending;public static CompletableFuture<Either<List<Entity>,WaystoneTeleportError>> future;
 public static Optional<Waystone>getWaystone(MinecraftServer server,UUID uid){return Optional.ofNullable(stones.get(uid));}
 public static Optional<Waystone>getWaystoneAt(ServerLevel level,BlockPos pos){return stones.values().stream().filter(s->s.dimension.equals(level.dimension())&&s.pos.equals(pos)).findFirst();}
 public static boolean isWaystoneActivated(ServerPlayer player,Waystone stone){return player.activated;}
 public static Stream<Waystone>getAllWaystones(MinecraftServer server){return stones.values().stream();}
 public static Either<WaystoneTeleportContext,WaystoneTeleportError>createDefaultTeleportContext(ServerPlayer player,Waystone target,Consumer<WaystoneTeleportContext> setup){
  creates++;var ctx=new WaystoneTeleportContext(player,target);setup.accept(ctx);
  if(originalDenied)return Either.right(new WaystoneTeleportError(net.minecraft.network.chat.Component.literal("Original Waystones permission/XP/cooldown denial")));
  return Either.left(ctx);
 }
 public static CompletableFuture<Either<List<Entity>,WaystoneTeleportError>>tryTeleportAsync(WaystoneTeleportContext context){starts++;pending=context;future=new CompletableFuture<>();return future;}
 public static void complete() throws Exception {
  var callback=new org.spongepowered.asm.mixin.injection.callback.CallbackInfoReturnable<Either<Void,WaystoneTeleportError>>("test",true);
  callback.setReturnValue(Either.left(null));
  var method=net.muxigame.core.compat.mixin.waystones.NetworkPendingTeleportMixin.class.getDeclaredMethod("muxi$validateImmediatelyBeforeCost",WaystoneTeleportContext.class,org.spongepowered.asm.mixin.injection.callback.CallbackInfoReturnable.class);method.setAccessible(true);method.invoke(null,pending,callback);
  if(callback.getReturnValue().right().isPresent()){future.complete(Either.right(callback.getReturnValue().right().get()));return;}
  fees++;var event=new net.blay09.mods.waystones.api.event.WaystoneTeleportEntityEvent.Pre(pending);net.blay09.mods.balm.api.Balm.getEvents().fire(event);
  if(event.override!=null){future.complete(Either.right(event.override.error()));return;}
  if(!noMovement){pending.player.level=pending.player.server.getLevel(pending.target.dimension);pending.player.pos=pending.target.pos;moves++;}
  future.complete(Either.left(List.of(pending.player)));
 }
}'''

files['NetworkRuntimeTest.java']='''import java.util.*;import java.nio.file.*;
import net.minecraft.core.*;import net.minecraft.server.*;import net.minecraft.server.level.*;
import net.muxigame.core.feature.dimensions.*;import net.muxigame.core.feature.waystones.*;import net.muxigame.core.feature.waystones.network.*;
import net.blay09.mods.waystones.api.*;import net.neoforged.neoforge.network.*;import net.neoforged.neoforge.network.event.*;
public class NetworkRuntimeTest {
 static int checks;static MinecraftServer server=new MinecraftServer();static ServerLevel home=new ServerLevel("minecraft:overworld"),away=new ServerLevel("muxi_game_core:overworld");
 static ServerPlayer player;static Waystone source,same,cross;static BlockPos gate=new BlockPos(3,65,0);static Path config;
 static void check(boolean pass,String message){checks++;if(!pass)throw new AssertionError(message);}
 static void request(UUID request,Waystone target){player.tickCount+=20;var packet=new WaystoneMapNetwork.Warp(request,target.uid);RegisterPayloadHandlersEvent.handlers.get(packet.type().id().toString()).accept(packet,new RegisterPayloadHandlersEvent.Context(player));}
 static WaystoneMapNetwork.Receipt last(){return (WaystoneMapNetwork.Receipt)PacketDistributor.sent.getLast();}
 static void registerGate(String dim,UUID stone) throws Exception {Files.createDirectories(config.getParent());Files.writeString(config,"{\\"version\\":1,\\"facilities\\":[{\\"dimension\\":\\""+dim+"\\",\\"portalPos\\":[3,65,0],\\"waystoneUid\\":\\""+stone+"\\"}]}");}
 static void realGate(boolean valid){home.blocks.put(gate,new WorldPortalBlock(1));if(valid)WorldPortals.frames.put(gate,new WorldPortals.Frame(new BlockPos(2,64,0),Direction.Axis.X,1));else WorldPortals.frames.remove(gate);}
 static Waystone stone(ServerLevel level,BlockPos pos){var stone=new Waystone(level.dimension(),pos);level.blocks.put(pos,new net.blay09.mods.waystones.block.WaystoneBlockBase());WaystonesAPI.stones.put(stone.uid,stone);return stone;}
 static void resetPlayer(){player.level=home;player.pos=new BlockPos(0,64,0);player.connection=new Object();player.activated=true;player.disconnected=false;}
 public static void main(String[] args) throws Exception {
  config=Path.of(System.getProperty("test.config")).resolve("muxi-game-core/teleport-network.json");
  server.levels.put(home.dimension(),home);server.levels.put(away.dimension(),away);home.server=server;away.server=server;player=new ServerPlayer(server,home);
  source=stone(home,new BlockPos(0,64,0));same=stone(home,new BlockPos(20,64,0));cross=stone(away,new BlockPos(40,64,0));
  WaystoneMapNetwork.register(new net.neoforged.bus.api.IEventBus());
  check(!Files.exists(config)&&NetworkPortalFacilities.config().facilities().isEmpty(),"absent file is empty and never created");
  var cfg=NetworkPortalFacilities.config();check(cfg.associationRadius()==4&&cfg.entranceRadius()==4&&cfg.associationVertical()==3&&cfg.entranceVertical()==3,"provisional defaults are separate ranges");
  check(NetworkPortalFacilities.source(player,cfg).stone()==source,"real nearby stone is source");
  UUID first=UUID.randomUUID();request(first,same);check(last().status().equals("pending")&&WaystonesAPI.moves==0,"ACK is pending, never success");
  request(UUID.randomUUID(),same);check(last().status().equals("failed")&&WaystonesAPI.starts==1,"one pending operation per connection");
  WaystonesAPI.complete();check(last().status().equals("completed")&&WaystonesAPI.fees==1&&WaystonesAPI.moves==1,"native final actual arrival and original fee");
  request(first,same);check(last().status().equals("completed")&&WaystonesAPI.starts==1,"request replay is idempotent");
  resetPlayer();request(UUID.randomUUID(),cross);check(last().message().contains("当前维度")&&WaystonesAPI.starts==1,"current dimension requires registered gateway");
  realGate(true);check(NetworkPortalFacilities.portalBadge(server,source,cfg),"player-built actual gate may add badge");
  check(!NetworkPortalFacilities.currentDimensionGateway(player,cfg),"player gate does not create facility authority");
  request(UUID.randomUUID(),cross);check(last().status().equals("failed"),"badge alone never authorizes cross-dimension warp");
  registerGate("muxi_game_core:overworld",cross.uid);cfg=NetworkPortalFacilities.config();check(!NetworkPortalFacilities.currentDimensionGateway(player,cfg),"target/other dimension gateway not current network");
  registerGate("minecraft:overworld",source.uid);cfg=NetworkPortalFacilities.config();check(NetworkPortalFacilities.currentDimensionGateway(player,cfg),"actual registered linked current gateway");
  server.levels.remove(away.dimension());check(!NetworkPortalFacilities.currentDimensionGateway(player,cfg),"facility gate destination must exist in actual server");server.levels.put(away.dimension(),away);
  home.blocks.put(gate,new WorldPortalBlock(0));WorldPortals.frames.put(gate,new WorldPortals.Frame(new BlockPos(2,64,0),Direction.Axis.X,0));check(!NetworkPortalFacilities.currentDimensionGateway(player,cfg),"same-dimension physical gate direction is not valid facility authority");realGate(true);
  realGate(false);check(!NetworkPortalFacilities.currentDimensionGateway(player,cfg),"broken/empty frame is not authority");realGate(true);
  home.loaded=false;check(!NetworkPortalFacilities.currentDimensionGateway(player,cfg)&&home.unloadedReads==0,"unloaded gate or stone fails without chunk reads/load");home.loaded=true;
  home.unloaded.add(gate.offset(3,0,3));check(!NetworkPortalFacilities.currentDimensionGateway(player,cfg)&&home.unloadedReads==0,"all neighbouring frame chunks checked before find");home.unloaded.clear();
  source.valid=false;check(!NetworkPortalFacilities.currentDimensionGateway(player,cfg),"destroyed registered stone disconnects");source.valid=true;
  registerGate("minecraft:overworld",UUID.randomUUID());check(!NetworkPortalFacilities.currentDimensionGateway(player,NetworkPortalFacilities.config()),"UID never resolves from a name or coordinate alone");registerGate("minecraft:overworld",source.uid);
  player.pos=new BlockPos(8,65,0);var facilitySource=NetworkPortalFacilities.source(player,NetworkPortalFacilities.config());check(facilitySource!=null&&facilitySource.facility()!=null,"registered connected gate fallback provides real associated source");
  Files.writeString(config,"{\\"version\\":1,\\"facilities\\":[]}");check(NetworkPortalFacilities.source(player,NetworkPortalFacilities.config())==null,"unregistered player gate cannot be entrance");registerGate("minecraft:overworld",source.uid);resetPlayer();
  player.activated=false;request(UUID.randomUUID(),cross);check(last().message().contains("激活"),"activation denied by server actor");cross.share=true;request(UUID.randomUUID(),cross);check(last().status().equals("pending"),"native Sharestone exception preserved");WaystonesAPI.complete();check(last().status().equals("completed"),"valid facility allows native cross dimension");cross.share=false;resetPlayer();
  WaystonesAPI.originalDenied=true;request(UUID.randomUUID(),same);check(last().message().contains("Original Waystones"),"original permissions/XP/cooldown errors preserved");WaystonesAPI.originalDenied=false;
  net.muxigame.minigames.GameRuntime.locked=true;request(UUID.randomUUID(),same);check(last().status().equals("failed"),"active game world travel restriction preserved");net.muxigame.minigames.GameRuntime.locked=false;
  away.loaded=false;request(UUID.randomUUID(),cross);check(last().status().equals("pending")&&NetworkTeleportGuard.denial(WaystonesAPI.pending)==null,"target chunk loading stays with native preparation, no premature client/world read");away.loaded=true;WaystonesAPI.complete();check(last().status().equals("completed"),"native prepared target can complete");resetPlayer();
  int fees=WaystonesAPI.fees;request(UUID.randomUUID(),cross);realGate(false);WaystonesAPI.complete();check(last().status().equals("failed")&&WaystonesAPI.fees==fees,"broken gate during async preparation cancels before consuming XP");realGate(true);resetPlayer();
  request(UUID.randomUUID(),cross);registerGate("minecraft:overworld",same.uid);WaystonesAPI.complete();check(last().status().equals("failed")&&WaystonesAPI.fees==fees,"association change during preparation cancels before cost");registerGate("minecraft:overworld",source.uid);resetPlayer();
  request(UUID.randomUUID(),same);player.pos=new BlockPos(100,64,0);WaystonesAPI.complete();check(last().status().equals("failed")&&WaystonesAPI.fees==fees,"moving away during preparation cancels");resetPlayer();
  request(UUID.randomUUID(),same);player.connection=new Object();int sent=PacketDistributor.sent.size();WaystonesAPI.complete();check(PacketDistributor.sent.size()==sent&&WaystonesAPI.fees==fees,"old async result cannot target a new connection");resetPlayer();
  request(UUID.randomUUID(),same);source.valid=false;WaystonesAPI.complete();check(last().status().equals("failed")&&WaystonesAPI.fees==fees,"destroyed source rechecked before movement/cost");source.valid=true;resetPlayer();
  request(UUID.randomUUID(),same);player.activated=false;WaystonesAPI.complete();check(last().status().equals("failed")&&WaystonesAPI.fees==fees,"activation rechecked after preparation");resetPlayer();
  request(UUID.randomUUID(),same);BlockPos oldTarget=same.pos;same.pos=same.pos.offset(1,0,0);WaystonesAPI.complete();check(last().status().equals("failed")&&WaystonesAPI.fees==fees,"mutable target object cannot move captured destination");same.pos=oldTarget;resetPlayer();
  request(UUID.randomUUID(),same);BlockPos oldSource=source.pos;source.pos=source.pos.offset(1,0,0);home.blocks.put(source.pos,new net.blay09.mods.waystones.block.WaystoneBlockBase());WaystonesAPI.complete();check(last().status().equals("failed")&&WaystonesAPI.fees==fees,"mutable source object cannot replace captured entrance");home.blocks.remove(source.pos);source.pos=oldSource;resetPlayer();
  request(UUID.randomUUID(),same);home.blocks.remove(same.pos);WaystonesAPI.complete();check(last().status().equals("failed")&&WaystonesAPI.fees==fees,"loaded target must still contain actual stone");home.blocks.put(same.pos,new net.blay09.mods.waystones.block.WaystoneBlockBase());resetPlayer();
  WaystonesAPI.noMovement=true;request(UUID.randomUUID(),cross);WaystonesAPI.complete();check(last().status().equals("failed"),"native result without actual matching dimension is never success");WaystonesAPI.noMovement=false;resetPlayer();
  Files.writeString(config,"{invalid");var legacy=new WaystoneMapNetwork.Teleport(cross.dimension.location(),cross.pos);RegisterPayloadHandlersEvent.handlers.get(legacy.type().id().toString()).accept(legacy,new RegisterPayloadHandlersEvent.Context(player));check(last().status().equals("failed")&&last().message().contains("当前维度"),"legacy packet cannot bypass cross-dimension guard");
  var request=new WaystoneMapNetwork.ViewRequest(UUID.randomUUID());RegisterPayloadHandlersEvent.handlers.get(request.type().id().toString()).accept(request,new RegisterPayloadHandlersEvent.Context(player));var view=(WaystoneMapNetwork.View)PacketDistributor.sent.getLast();check(!view.crossDimensionReady()&&view.nodes().size()==3,"real view no fake portal nodes");
  player.activated=false;player.tickCount+=40;RegisterPayloadHandlersEvent.handlers.get(request.type().id().toString()).accept(request,new RegisterPayloadHandlersEvent.Context(player));check(((WaystoneMapNetwork.View)PacketDistributor.sent.getLast()).nodes().isEmpty(),"private unactivated stones not exposed");
  var buffer=new net.minecraft.network.RegistryFriendlyByteBuf();WaystoneMapNetwork.View.CODEC.encode(buffer,view);check(WaystoneMapNetwork.View.CODEC.decode(buffer).equals(view),"bounded actual view codec roundtrip");
  var bad=new net.minecraft.network.RegistryFriendlyByteBuf();bad.writeUUID(UUID.randomUUID());bad.writeResourceLocation(home.dimension().location());bad.writeBoolean(false);bad.writeBoolean(false);bad.writeVarInt(257);try{WaystoneMapNetwork.View.CODEC.decode(bad);throw new AssertionError("oversize accepted");}catch(io.netty.handler.codec.DecoderException expected){checks++;}
  check(home.worldWrites==0&&away.worldWrites==0,"no world blocks, facilities or exit gates created");
  check(NetworkTeleportGuard.denial(new WaystoneTeleportContext(player,same))==null,"unowned native context unaffected");
  player.activated=true;Object retainedConnection=player.connection;player=new ServerPlayer(server,home);player.connection=retainedConnection;
  var renewed=new WaystoneMapNetwork.ViewRequest(UUID.randomUUID());RegisterPayloadHandlersEvent.handlers.get(renewed.type().id().toString()).accept(renewed,new RegisterPayloadHandlersEvent.Context(player));check(((WaystoneMapNetwork.View)PacketDistributor.sent.getLast()).request().equals(renewed.request()),"new player identity on retained connection does not inherit old tick throttle");
  System.out.println("{\\"success\\":true,\\"checks\\":"+checks+",\\"scope\\":\\"production facility adapter/server protocol/guard hooks with controlled world and native Waystones doubles; no Minecraft launch\\"}");
 }
}'''

def run():
 out=root/'evidence';out.mkdir(exist_ok=True)
 aggregate=Path(os.environ.get('TASK6_COMPILER_DEPENDENCIES','C:/Users/Administrator/Documents/Codex/2026-10-01/task-21/music-app/build/compiler-dependencies.jar'))
 with tempfile.TemporaryDirectory(dir=out) as temp:
  temp=Path(temp);sources=[]
  for name,text in files.items():
   path=temp/name;path.parent.mkdir(parents=True,exist_ok=True);path.write_text(text,encoding='utf-8');sources.append(path)
  base=root/'muxi-game-core/src/main/java/net/muxigame/core'
  sources+=[base/'feature/waystones/WaystoneMapNetwork.java',*sorted((base/'feature/waystones/network').glob('*.java')),base/'compat/mixin/waystones/NetworkPendingTeleportMixin.java']
  args=temp/'compile.args';opts=['--release','21','-encoding','UTF-8','-proc:none','-cp',str(aggregate),'-d',str(temp/'classes'),*map(str,sources)]
  args.write_text('\n'.join('"'+a.replace('\\','/')+'"' for a in opts),encoding='utf-8')
  result=subprocess.run(['C:/Program Files/Java/jdk-24/bin/javac.exe','@'+str(args)],capture_output=True)
  if result.returncode:print(result.stderr.decode('utf-8','replace'));result.check_returncode()
  result=subprocess.run(['C:/Program Files/Java/jdk-24/bin/java.exe','-Dtest.config='+str(temp/'config'),'-cp',str(temp/'classes')+os.pathsep+str(aggregate),'NetworkRuntimeTest'],capture_output=True)
  if result.returncode:print(result.stderr.decode('utf-8','replace'));result.check_returncode()
  report=json.loads(result.stdout);(out/'network-runtime-result.json').write_text(json.dumps(report,indent=2)+'\n',encoding='utf-8');print(json.dumps(report))

if __name__=='__main__':run()
